import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-reactive-forms',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './reactive-forms.component.html',
  styleUrl: './reactive-forms.component.css',
})
export class ReactiveFormsComponent {
  syntaxCode = [
    '// Import ReactiveFormsModule (standalone component or NgModule)',
    'import { ReactiveFormsModule } from "@angular/forms";',
    'import { FormBuilder, FormGroup, Validators } from "@angular/forms";',
    '',
    '@Component({',
    '  imports: [ReactiveFormsModule],',
    '})',
    'export class MyComponent {',
    '  form: FormGroup;',
    '',
    '  constructor(private fb: FormBuilder) {',
    '    this.form = this.fb.group({',
    '      email: ["", [Validators.required, Validators.email]],',
    '      password: ["", [Validators.required, Validators.minLength(6)]],',
    '    });',
    '  }',
    '',
    '  // Access a specific control',
    '  get email() { return this.form.get("email"); }',
    '',
    '  // Read form value and validity',
    '  onSubmit() {',
    '    if (this.form.valid) {',
    '      console.log(this.form.value); // { email: "...", password: "..." }',
    '    }',
    '  }',
    '',
    '  // React to value changes with RxJS',
    '  ngOnInit() {',
    '    this.form.get("email")!.valueChanges.subscribe(val => {',
    '      console.log("Email changed:", val);',
    '    });',
    '  }',
    '}',
  ].join('\n');

  exampleCode = [
    '// registration.component.ts',
    'export class RegistrationComponent implements OnInit {',
    '  form!: FormGroup;',
    '',
    '  constructor(private fb: FormBuilder) {}',
    '',
    '  ngOnInit() {',
    '    this.form = this.fb.group({',
    '      name:     ["", Validators.required],',
    '      email:    ["", [Validators.required, Validators.email]],',
    '      password: ["", [Validators.required, Validators.minLength(8)]],',
    '    });',
    '',
    '    // Real-time feedback via RxJS observable',
    '    this.form.get("email")!.valueChanges.subscribe(v => {',
    '      console.log("Email live value:", v);',
    '    });',
    '  }',
    '',
    '  // setValue: ALL fields must be supplied',
    '  prefillAll() {',
    '    this.form.setValue({',
    '      name: "Alice", email: "alice@example.com", password: "secret123",',
    '    });',
    '  }',
    '',
    '  // patchValue: supply only the fields you want to update',
    '  prefillEmail() {',
    '    this.form.patchValue({ email: "alice@example.com" });',
    '  }',
    '',
    '  onRegister() {',
    '    if (this.form.valid) {',
    '      console.log("Register:", this.form.value);',
    '      this.form.reset();',
    '    }',
    '  }',
    '}',
    '',
    '<!-- registration.component.html -->',
    '<form [formGroup]="form" (ngSubmit)="onRegister()">',
    '  <input formControlName="name" placeholder="Name" />',
    '  <input formControlName="email" type="email" placeholder="Email" />',
    '  <input formControlName="password" type="password" placeholder="Password" />',
    '  <button type="submit" [disabled]="form.invalid">Register</button>',
    '</form>',
  ].join('\n');

  interviewQA = [
    {
      q: 'What are Reactive Forms and which module do they require?',
      a: 'Reactive Forms are Angular\'s TypeScript-first forms approach where the form model (FormGroup, FormControl, FormArray) is created explicitly in the component class. The template binds to this model via [formGroup] and formControlName directives. They require ReactiveFormsModule to be imported.',
    },
    {
      q: 'What is the difference between FormBuilder and manually creating FormGroup?',
      a: 'Both produce the same result. FormBuilder (injected via DI) is a shorthand service: this.fb.group({}) and this.fb.control() reduce boilerplate. Writing new FormGroup({ email: new FormControl("") }) manually is equivalent but more verbose. FormBuilder is preferred for readability in real projects.',
    },
    {
      q: 'What is the difference between setValue and patchValue?',
      a: 'setValue requires you to supply values for ALL controls in the FormGroup — passing a partial object throws an error. patchValue accepts a partial object and only updates the keys you provide, leaving other controls untouched. Use patchValue when pre-filling only some fields.',
    },
    {
      q: 'What are valueChanges and statusChanges and how are they used?',
      a: 'Both are RxJS Observables exposed by every AbstractControl. valueChanges emits the current value on every keystroke. statusChanges emits the current validity status ("VALID", "INVALID", "PENDING", "DISABLED") whenever it changes. They enable real-time feedback, debounced search, cross-field validation, and conditional UI — all without imperative DOM code.',
    },
    {
      q: 'How do you dynamically add or remove controls in a Reactive Form?',
      a: 'Use FormGroup.addControl(name, control) to add a new control at runtime and FormGroup.removeControl(name) to remove one. For variable-length lists, use FormArray with its push(), removeAt(), and clear() methods. This is much easier than in Template-Driven Forms, which require structural directive tricks.',
    },
    {
      q: 'When should you choose Reactive Forms over Template-Driven Forms?',
      a: 'Choose Reactive Forms when: the form is complex or has many inter-dependent fields; fields are added/removed dynamically; you need unit-testable form logic without the DOM; you want to leverage RxJS (debounce, switchMap for async validation); or the team prefers explicit, predictable TypeScript over implicit template magic.',
    },
    {
      q: 'What does form.reset() do in Reactive Forms?',
      a: 'form.reset() clears all control values back to null (or the initial value if a reset object is passed) and resets all state flags: pristine, untouched, and valid. Optionally pass an object to reset to specific values: form.reset({ email: "default@email.com" }). It does NOT destroy or recreate the FormGroup.',
    },
  ];
}
