import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-token-interceptor',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './token-interceptor.component.html',
  styleUrl: './token-interceptor.component.css',
})
export class TokenInterceptorComponent {
  syntaxCode = [
    '// Token Interceptor — attach Bearer JWT to every API request',
    '// Uses functional interceptor (Angular 15+)',
    '',
    'import { HttpInterceptorFn, HttpContextToken } from "@angular/common/http";',
    'import { inject } from "@angular/core";',
    '',
    '// Context token to skip auth for specific requests',
    'export const SKIP_AUTH = new HttpContextToken<boolean>(() => false);',
    '',
    'export const tokenInterceptor: HttpInterceptorFn = (req, next) => {',
    '  const authService = inject(AuthService);',
    '',
    '  // Skip auth header for requests marked SKIP_AUTH',
    '  if (req.context.get(SKIP_AUTH)) {',
    '    return next(req);',
    '  }',
    '',
    '  const token = authService.getAccessToken();',
    '',
    '  if (!token) {',
    '    return next(req); // No token — send request as-is',
    '  }',
    '',
    '  // Clone and add Authorization header (request is immutable)',
    '  const authReq = req.clone({',
    '    headers: req.headers.set("Authorization", `Bearer ${token}`)',
    '  });',
    '',
    '  return next(authReq);',
    '};',
  ].join('\n');

  exampleCode = [
    '// Real-world: Token interceptor skipping /auth endpoints',
    '',
    '// AuthService — centralized token management',
    '@Injectable({ providedIn: "root" })',
    'export class AuthService {',
    '  private accessToken: string | null = null; // Stored in memory (safest)',
    '',
    '  setToken(token: string) { this.accessToken = token; }',
    '  getAccessToken(): string | null { return this.accessToken; }',
    '  clearToken() { this.accessToken = null; }',
    '',
    '  isLoggedIn(): boolean {',
    '    if (!this.accessToken) return false;',
    '    try {',
    '      const payload = JSON.parse(atob(this.accessToken.split(".")[1]));',
    '      return payload.exp > Date.now() / 1000; // Check expiry',
    '    } catch { return false; }',
    '  }',
    '}',
    '',
    '// Token interceptor with public endpoint skipping',
    'const PUBLIC_URLS = ["/api/auth/login", "/api/auth/register", "/api/public"];',
    '',
    'export const tokenInterceptor: HttpInterceptorFn = (req, next) => {',
    '  const authService = inject(AuthService);',
    '',
    '  // Skip token for public endpoints',
    '  const isPublic = PUBLIC_URLS.some(url => req.url.includes(url));',
    '  if (isPublic || req.context.get(SKIP_AUTH)) {',
    '    return next(req);',
    '  }',
    '',
    '  const token = authService.getAccessToken();',
    '  if (!token) return next(req);',
    '',
    '  return next(req.clone({',
    '    setHeaders: { Authorization: `Bearer ${token}` }',
    '  }));',
    '};',
    '',
    '// Usage — skip auth for a specific call:',
    '// this.http.post("/api/auth/login", body, {',
    '//   context: new HttpContext().set(SKIP_AUTH, true)',
    '// })',
  ].join('\n');

  interviewQA = [
    {
      q: 'What is a token interceptor and what does it do?',
      a: 'A token interceptor is an Angular HTTP interceptor whose specific responsibility is reading the current authentication token (JWT) and attaching it as an Authorization: Bearer <token> header to every outgoing HTTP request. Without this interceptor, every service method calling the API would need to manually add the header — a clear DRY violation. The interceptor handles it transparently: the service makes a plain http.get() call and the header is added automatically.',
    },
    {
      q: 'How do you skip the token interceptor for public endpoints like /login and /register?',
      a: 'Two approaches: (1) URL check: const PUBLIC = ["/auth/login", "/auth/register"]; if (PUBLIC.some(url => req.url.includes(url))) return next(req); — simple but fragile (URL strings change). (2) HttpContext token (Angular 12+, recommended): define export const SKIP_AUTH = new HttpContextToken(() => false); check in the interceptor if (req.context.get(SKIP_AUTH)) return next(req); and pass context when making the request: this.http.post("/login", body, { context: new HttpContext().set(SKIP_AUTH, true) }). The context approach is cleaner and environment-agnostic.',
    },
    {
      q: 'Should you store the access token in localStorage or memory for the interceptor to read?',
      a: 'Memory (component/service property) is the safest option — the token is never written to disk and cannot be stolen by XSS. localStorage is convenient but XSS-vulnerable. Best practice for security: store the refresh token in an httpOnly cookie (server-set) and the access token in memory. The AuthService holds a private accessToken: string | null property. On page refresh, the app uses the refresh token (from the cookie) to silently obtain a new access token into memory. The token interceptor reads from the AuthService memory property.',
    },
    {
      q: 'What is the difference between req.clone({ headers: ... }) and req.clone({ setHeaders: ... })?',
      a: 'Both modify headers on the cloned request. headers: req.headers.set("Authorization", "Bearer ...") replaces the entire headers object — you must explicitly copy existing headers if you want to preserve them. setHeaders: { Authorization: "Bearer ..." } is a shorthand that MERGES the provided headers with the existing headers automatically. For adding a single header (like Authorization), setHeaders is simpler and less error-prone since it preserves all existing headers without any explicit copying.',
    },
    {
      q: 'How do you handle the case where the token is null in the token interceptor?',
      a: 'If no token is available (user is not logged in or token was cleared), simply pass the request through without adding the Authorization header: if (!token) return next(req). The backend will return a 401 for protected routes, which should be handled by a separate error interceptor. Do not throw an error or cancel the request in the token interceptor — that is not its job. Some requests (login page, public API) are intentionally made without a token and should succeed.',
    },
    {
      q: 'Can the token interceptor access route guards or router state?',
      a: 'Yes, using inject() inside a functional interceptor. You can inject the Router, ActivatedRoute, or any Angular service: const router = inject(Router). However, accessing route state in the interceptor is typically an anti-pattern — interceptors should be stateless request/response transformers. If the routing state determines whether to add a token, that logic likely belongs in the route guard (which should redirect to /login before the request is even made) or in the service method. Interceptors should only look at the request and the token, not router state.',
    },
    {
      q: 'How do you refresh the token inside the token interceptor when it is expired?',
      a: 'Token refresh in the interceptor should be handled by a dedicated error interceptor (or a combined auth interceptor) that watches for 401 responses, not in the token interceptor itself. The token interceptor\'s single responsibility is attaching the current token. When a 401 is returned, the error interceptor calls AuthService.refreshToken(), updates the in-memory access token, and retries the failed request. Separating these concerns (token attachment vs. token refresh) keeps each interceptor focused and testable.',
    },
  ];
}
