import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-refresh-token',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './refresh-token.component.html',
  styleUrl: './refresh-token.component.css',
})
export class RefreshTokenComponent {
  syntaxCode = [
    '// Access token vs Refresh token',
    '',
    '// Access Token: short-lived (5-15 minutes)',
    '// Used in Authorization: Bearer <token> header',
    '// Stateless, signed JWT',
    '',
    '// Refresh Token: long-lived (7-30 days)',
    '// Stored in httpOnly cookie (XSS-safe)',
    '// Opaque or JWT, stored in DB for revocation',
    '',
    '// Silent refresh flow:',
    '// 1. Access token expires → API returns 401',
    '// 2. Interceptor catches 401',
    '// 3. Interceptor calls POST /auth/refresh (sends refresh token cookie)',
    '// 4. Server validates refresh token, issues new access token',
    '// 5. Interceptor retries original request with new access token',
    '// 6. User never sees a login screen',
    '',
    '// Token rotation:',
    '// Each refresh also issues a new refresh token',
    '// Old refresh token is invalidated → prevents replay attacks',
  ].join('\n');

  exampleCode = [
    '// Angular HTTP Interceptor with token refresh queue',
    '',
    '@Injectable()',
    'export class TokenRefreshInterceptor implements HttpInterceptor {',
    '  private isRefreshing = false;',
    '  private refreshSubject = new BehaviorSubject<string | null>(null);',
    '',
    '  constructor(private authService: AuthService) {}',
    '',
    '  intercept(req: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {',
    '    return next.handle(req).pipe(',
    '      catchError(error => {',
    '        if (error instanceof HttpErrorResponse && error.status === 401) {',
    '          return this.handle401(req, next);',
    '        }',
    '        return throwError(() => error);',
    '      })',
    '    );',
    '  }',
    '',
    '  private handle401(req: HttpRequest<any>, next: HttpHandler) {',
    '    if (!this.isRefreshing) {',
    '      this.isRefreshing = true;',
    '      this.refreshSubject.next(null); // Signal: refresh in progress',
    '',
    '      return this.authService.refreshToken().pipe(',
    '        switchMap(newToken => {',
    '          this.isRefreshing = false;',
    '          this.refreshSubject.next(newToken); // Broadcast new token',
    '          return next.handle(this.addToken(req, newToken));',
    '        }),',
    '        catchError(err => {',
    '          this.isRefreshing = false;',
    '          this.authService.logout();',
    '          return throwError(() => err);',
    '        })',
    '      );',
    '    }',
    '    // Queue other 401 requests until refresh completes',
    '    return this.refreshSubject.pipe(',
    '      filter(token => token !== null),',
    '      take(1),',
    '      switchMap(token => next.handle(this.addToken(req, token!)))',
    '    );',
    '  }',
    '',
    '  private addToken(req: HttpRequest<any>, token: string) {',
    '    return req.clone({ headers: req.headers.set("Authorization", `Bearer ${token}`) });',
    '  }',
    '}',
  ].join('\n');

  interviewQA = [
    {
      q: 'What is a refresh token and why is it needed?',
      a: 'A refresh token is a long-lived credential (typically 7-30 days) used to obtain new access tokens without requiring the user to log in again. Access tokens are kept short-lived (5-15 minutes) to limit the damage if one is stolen — if an attacker gets an access token, it expires quickly. The refresh token enables "silent refresh": when the access token expires, the app quietly exchanges the refresh token for a new access token, creating a seamless user experience without repeated login prompts.',
    },
    {
      q: 'How does silent token refresh work in an Angular interceptor?',
      a: 'The interceptor wraps every HTTP call with catchError. When a 401 response is received, the interceptor calls authService.refreshToken() which POSTs to /auth/refresh (the refresh token is in an httpOnly cookie, so it is sent automatically). The server validates the refresh token, issues a new access token, and returns it. The interceptor then retries the original failed request with the new token — all transparently, without the user seeing a login screen.',
    },
    {
      q: 'What is the token refresh queue problem and how do you solve it?',
      a: 'The refresh queue problem occurs when multiple API calls fail with 401 simultaneously (e.g., a page loads and makes 5 parallel requests, all with an expired token). Without coordination, each interceptor call would independently try to refresh, causing 5 simultaneous refresh requests and potentially invalidating each other. The solution is a BehaviorSubject flag: the first 401 sets isRefreshing = true and starts the refresh. Subsequent 401s queue up by filtering on the BehaviorSubject and waiting for the new token before retrying.',
    },
    {
      q: 'What is token rotation and why is it important?',
      a: 'Token rotation means the server issues a new refresh token on every refresh request and immediately invalidates the old one. This prevents refresh token replay attacks — if an attacker steals a refresh token and tries to use it after the legitimate user has already used it, the token will be invalid (already rotated). The server can detect when a rotated (already-used) refresh token is submitted and treat it as a sign of token theft, triggering logout of all sessions for that user.',
    },
    {
      q: 'How should refresh tokens be stored in an Angular app?',
      a: 'Refresh tokens should be stored in httpOnly, Secure, SameSite=Strict cookies set by the server. httpOnly prevents JavaScript from reading the token, protecting against XSS. SameSite=Strict prevents the cookie from being sent in cross-site requests, mitigating CSRF. The Angular client never directly handles the refresh token — it just calls the /auth/refresh endpoint, and the browser automatically sends the cookie. This way, even if an XSS attack executes JavaScript, it cannot steal the refresh token.',
    },
    {
      q: 'When should you force logout instead of refreshing the token?',
      a: 'Force logout (redirect to /login, clear tokens) when: (1) the /auth/refresh endpoint itself returns 401 or 403 — the refresh token is expired or revoked; (2) the server returns a 401 with a specific error code indicating the refresh token was stolen (detected via rotation); (3) the user deliberately logs out. In the interceptor\'s catchError for the refresh call, call authService.logout() (which clears tokens and navigates to login) instead of retrying. Never loop infinitely on refresh failures.',
    },
    {
      q: 'What is the difference between access token and refresh token storage strategies?',
      a: 'Access tokens are short-lived so the risk from localStorage/memory storage is lower, but they can be stored in memory (safest — lost on refresh, mitigated by refresh token) or localStorage (convenient but XSS risk). Refresh tokens are long-lived and must be stored in httpOnly cookies (server-set, JS-inaccessible). Never store refresh tokens in localStorage or sessionStorage. The access token goes in the Authorization header; the refresh token cookie is sent automatically by the browser to the /auth/refresh endpoint.',
    },
  ];
}
