import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-component-lifecycle',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './component-lifecycle.component.html',
  styleUrl: './component-lifecycle.component.css',
})
export class ComponentLifecycleComponent {
  syntaxCode = [
    "import { Component, OnInit, OnDestroy, OnChanges,",
    '         SimpleChanges, AfterViewInit, AfterViewChecked,',
    "         AfterContentInit, AfterContentChecked, DoCheck } from '@angular/core';",
    '',
    '@Component({ selector: \'app-example\', standalone: true, template: \'...\' })',
    'export class ExampleComponent implements',
    '    OnChanges, OnInit, DoCheck,',
    '    AfterContentInit, AfterContentChecked,',
    '    AfterViewInit, AfterViewChecked, OnDestroy {',
    '',
    '  // 1. Called before ngOnInit when @Input changes',
    '  ngOnChanges(changes: SimpleChanges) {',
    '    console.log(\'Input changed:\', changes);',
    '  }',
    '',
    '  // 2. Called once after first ngOnChanges — ideal for init logic',
    '  ngOnInit() {',
    '    this.loadData();',
    '  }',
    '',
    '  // 3. Custom change detection (every CD cycle)',
    '  ngDoCheck() { }',
    '',
    '  // 4. After ng-content is projected',
    '  ngAfterContentInit() { }',
    '',
    '  // 5. After projected content is checked',
    '  ngAfterContentChecked() { }',
    '',
    '  // 6. After component\'s view & child views are initialized',
    '  ngAfterViewInit() {',
    '    // Safe to access @ViewChild here',
    '  }',
    '',
    '  // 7. After every check of the component\'s view',
    '  ngAfterViewChecked() { }',
    '',
    '  // 8. Called just before the component is destroyed',
    '  ngOnDestroy() {',
    '    this.subscription.unsubscribe();',
    '  }',
    '}',
  ].join('\n');

  exampleCode = [
    '// data-dashboard.component.ts — real-world lifecycle usage',
    "import { Component, Input, OnInit, OnDestroy, OnChanges, SimpleChanges } from '@angular/core';",
    "import { Subscription } from 'rxjs';",
    "import { DataService } from './data.service';",
    '',
    '@Component({ selector: \'app-dashboard\', standalone: true, template: \'...\' })',
    'export class DataDashboardComponent implements OnInit, OnChanges, OnDestroy {',
    "  @Input() userId: string = '';",
    '  userData: any = null;',
    '  private sub!: Subscription;',
    '',
    '  constructor(private dataService: DataService) {}',
    '',
    '  // Called when userId @Input changes',
    '  ngOnChanges(changes: SimpleChanges) {',
    "    if (changes['userId'] && !changes['userId'].firstChange) {",
    '      this.loadUserData(this.userId); // reload when user changes',
    '    }',
    '  }',
    '',
    '  // Initial data load',
    '  ngOnInit() {',
    '    this.loadUserData(this.userId);',
    '    this.sub = this.dataService.updates$.subscribe(update => {',
    '      this.userData = update;',
    '    });',
    '  }',
    '',
    '  private loadUserData(id: string) {',
    '    this.dataService.getUser(id).subscribe(u => this.userData = u);',
    '  }',
    '',
    '  // Cleanup subscriptions to prevent memory leaks',
    '  ngOnDestroy() {',
    '    this.sub.unsubscribe();',
    '  }',
    '}',
  ].join('\n');

  interviewQA = [
    {
      q: 'What are the 8 Angular lifecycle hooks and in what order do they execute?',
      a: 'The order is: (1) ngOnChanges — when @Input changes; (2) ngOnInit — once after first ngOnChanges; (3) ngDoCheck — every change detection cycle; (4) ngAfterContentInit — after ng-content projection; (5) ngAfterContentChecked — after projected content is checked; (6) ngAfterViewInit — after the component view and child views are initialized; (7) ngAfterViewChecked — after every check of the view; (8) ngOnDestroy — just before the component is destroyed.',
    },
    {
      q: 'What is the difference between ngOnInit and the constructor?',
      a: 'The constructor is a TypeScript feature that runs when the class is instantiated. At that point, Angular has not yet set @Input properties or rendered the view. ngOnInit is an Angular lifecycle hook called after Angular sets all @Input bindings. Best practice: use the constructor only for dependency injection and simple property initialization; use ngOnInit for any logic that depends on @Input values, HTTP calls, or subscriptions.',
    },
    {
      q: 'When is ngOnChanges called and what does SimpleChanges contain?',
      a: 'ngOnChanges is called before ngOnInit and then every time an @Input property changes. SimpleChanges is an object map where each key is the @Input property name, and the value is a SimpleChange object with: previousValue, currentValue, and firstChange (boolean). Use it to react to specific input changes and avoid unnecessary work on first render by checking firstChange.',
    },
    {
      q: 'Why is ngOnDestroy important and what should you clean up there?',
      a: 'ngOnDestroy prevents memory leaks by cleaning up resources before the component is removed from the DOM. You should: (1) unsubscribe from RxJS subscriptions; (2) clear setInterval/setTimeout timers; (3) remove event listeners added with addEventListener; (4) close WebSocket connections. Using the takeUntilDestroyed() operator (Angular 16+) or a Subject with takeUntil is a cleaner pattern.',
    },
    {
      q: 'What is the difference between ngAfterViewInit and ngAfterContentInit?',
      a: 'ngAfterContentInit fires after content projected via ng-content is initialized — this is when @ContentChild/@ContentChildren become available. ngAfterViewInit fires after the component\'s own template and all child component views are initialized — this is when @ViewChild/@ViewChildren become available. ngAfterContentInit always fires before ngAfterViewInit.',
    },
    {
      q: 'When would you use ngDoCheck over ngOnChanges?',
      a: 'ngOnChanges only detects changes to @Input reference values (shallow equality). ngDoCheck runs every change detection cycle and lets you implement custom change detection logic — for example, detecting mutations inside an array or object passed as @Input (since the reference doesn\'t change). Be careful: ngDoCheck runs very frequently, so keep its logic minimal to avoid performance issues.',
    },
  ];
}
