import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-coding-questions',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './coding-questions.component.html',
  styleUrl: './coding-questions.component.css',
})
export class CodingQuestionsComponent {
  questions = [
    {
      id: 1,
      title: 'Create a basic standalone component',
      code: [
        'import { Component } from "@angular/core";',
        '',
        '@Component({',
        '  selector: "app-hello",',
        '  standalone: true,',
        '  template: `<h1>Hello, {{ name }}!</h1>`,',
        '})',
        'export class HelloComponent {',
        '  name = "Angular";',
        '}',
      ].join('\n'),
      explanation: 'A standalone component sets standalone: true in the decorator. It does not belong to any NgModule. The template is inline here for brevity; use templateUrl for real components.',
    },
    {
      id: 2,
      title: 'Create and inject a service',
      code: [
        '// user.service.ts',
        '@Injectable({ providedIn: "root" })',
        'export class UserService {',
        '  getUsers(): Observable<User[]> {',
        '    return this.http.get<User[]>("/api/users");',
        '  }',
        '  constructor(private http: HttpClient) {}',
        '}',
        '',
        '// component.ts',
        'export class UserListComponent {',
        '  users$ = this.userService.getUsers();',
        '  constructor(private userService: UserService) {}',
        '}',
      ].join('\n'),
      explanation: 'providedIn: "root" registers the service as a singleton at the root injector. Angular\'s DI injects it via the constructor. Using inject() function is the modern alternative to constructor injection.',
    },
    {
      id: 3,
      title: 'Set up routing with lazy-loaded standalone component',
      code: [
        '// app.routes.ts',
        'export const routes: Routes = [',
        '  { path: "", component: HomeComponent },',
        '  {',
        '    path: "products",',
        '    loadComponent: () => import("./products/products.component")',
        '                         .then(m => m.ProductsComponent)',
        '  },',
        '  { path: "**", redirectTo: "" }',
        '];',
        '',
        '// main.ts',
        'bootstrapApplication(AppComponent, {',
        '  providers: [provideRouter(routes)]',
        '});',
      ].join('\n'),
      explanation: 'loadComponent lazily loads a standalone component on demand. The dynamic import creates a separate code chunk, reducing initial bundle size. redirectTo handles unknown URLs.',
    },
    {
      id: 4,
      title: 'Build a reactive form with validation',
      code: [
        'import { FormBuilder, Validators, ReactiveFormsModule } from "@angular/forms";',
        '',
        '@Component({',
        '  imports: [ReactiveFormsModule, CommonModule],',
        '  template: `',
        '    <form [formGroup]="form" (ngSubmit)="submit()">',
        '      <input formControlName="email" />',
        '      <span *ngIf="form.get(\'email\')?.hasError(\'required\')">Required</span>',
        '      <span *ngIf="form.get(\'email\')?.hasError(\'email\')">Invalid email</span>',
        '      <button type="submit" [disabled]="form.invalid">Submit</button>',
        '    </form>',
        '  `',
        '})',
        'export class LoginComponent {',
        '  form = inject(FormBuilder).group({',
        '    email: ["", [Validators.required, Validators.email]],',
        '    password: ["", [Validators.required, Validators.minLength(8)]]',
        '  });',
        '  submit() { if (this.form.valid) console.log(this.form.value); }',
        '}',
      ].join('\n'),
      explanation: 'FormBuilder.group() creates a FormGroup. Validators.required and Validators.email are built-in validators. [disabled]="form.invalid" prevents submit when form is invalid. Use hasError() to show field-level error messages.',
    },
    {
      id: 5,
      title: 'Make an HTTP GET request with error handling',
      code: [
        '@Injectable({ providedIn: "root" })',
        'export class ProductService {',
        '  private http = inject(HttpClient);',
        '  private products$ = new BehaviorSubject<Product[]>([]);',
        '',
        '  getProducts(): Observable<Product[]> {',
        '    return this.http.get<Product[]>("/api/products").pipe(',
        '      catchError(err => {',
        '        console.error("Failed to load products:", err);',
        '        return of([]);',
        '      })',
        '    );',
        '  }',
        '}',
      ].join('\n'),
      explanation: 'HttpClient.get<T>() returns an Observable that emits once and completes. catchError intercepts errors and returns a fallback Observable (of([])) so the stream does not terminate with an error. Always handle HTTP errors gracefully.',
    },
    {
      id: 6,
      title: 'Create a custom pipe',
      code: [
        'import { Pipe, PipeTransform } from "@angular/core";',
        '',
        '@Pipe({ name: "truncate", standalone: true })',
        'export class TruncatePipe implements PipeTransform {',
        '  transform(value: string, limit = 50, ellipsis = "..."): string {',
        '    if (!value) return "";',
        '    return value.length > limit',
        '      ? value.substring(0, limit) + ellipsis',
        '      : value;',
        '  }',
        '}',
        '',
        '// Usage in template:',
        '// {{ longText | truncate:100 }}',
        '// {{ longText | truncate:30:"..." }}',
      ].join('\n'),
      explanation: 'A pipe implements PipeTransform with a transform() method. The first argument is the piped value; subsequent arguments are passed after the colon in the template. standalone: true allows direct import into components.',
    },
    {
      id: 7,
      title: 'Create a custom structural directive',
      code: [
        'import { Directive, Input, TemplateRef, ViewContainerRef } from "@angular/core";',
        '',
        '@Directive({ selector: "[appIfRole]", standalone: true })',
        'export class IfRoleDirective {',
        '  private currentRole = inject(AuthService).currentRole;',
        '',
        '  @Input() set appIfRole(allowedRoles: string[]) {',
        '    const hasRole = allowedRoles.includes(this.currentRole);',
        '    if (hasRole) {',
        '      this.vcr.createEmbeddedView(this.tpl);',
        '    } else {',
        '      this.vcr.clear();',
        '    }',
        '  }',
        '',
        '  constructor(',
        '    private tpl: TemplateRef<any>,',
        '    private vcr: ViewContainerRef',
        '  ) {}',
        '}',
        '',
        '// Usage: <div *appIfRole="[\'admin\', \'manager\']">Admin only</div>',
      ].join('\n'),
      explanation: 'Structural directives manipulate the DOM by adding/removing elements. TemplateRef holds the template content; ViewContainerRef manages where it is inserted. The * syntax desugars to [appIfRole]="" on an ng-template.',
    },
    {
      id: 8,
      title: 'Implement all lifecycle hooks',
      code: [
        '@Component({ ... })',
        'export class LifecycleComponent implements OnInit, OnChanges, DoCheck,',
        '    AfterContentInit, AfterContentChecked,',
        '    AfterViewInit, AfterViewChecked, OnDestroy {',
        '',
        '  @Input() data: any;',
        '',
        '  ngOnChanges(changes: SimpleChanges) { /* @Input changed */ }',
        '  ngOnInit()           { /* setup: called once after first ngOnChanges */ }',
        '  ngDoCheck()          { /* custom change detection */ }',
        '  ngAfterContentInit() { /* ng-content projected */ }',
        '  ngAfterContentChecked() { /* after content checked */ }',
        '  ngAfterViewInit()    { /* ViewChild available */ }',
        '  ngAfterViewChecked() { /* after view checked */ }',
        '  ngOnDestroy()        { /* cleanup subscriptions, timers */ }',
        '}',
      ].join('\n'),
      explanation: 'Hook order: OnChanges → OnInit → DoCheck → AfterContentInit → AfterContentChecked → AfterViewInit → AfterViewChecked → (repeat DoCheck, AfterContentChecked, AfterViewChecked on CD) → OnDestroy. OnInit is the main setup hook; OnDestroy is for cleanup.',
    },
    {
      id: 9,
      title: 'Use @ViewChild to access a child component',
      code: [
        '@Component({',
        '  template: `',
        '    <app-counter #counter />',
        '    <button (click)="reset()">Reset Counter</button>',
        '  `',
        '})',
        'export class ParentComponent implements AfterViewInit {',
        '  @ViewChild("counter") counterRef!: CounterComponent;',
        '',
        '  ngAfterViewInit() {',
        '    // ViewChild is available from AfterViewInit onwards',
        '    console.log(this.counterRef.count);',
        '  }',
        '',
        '  reset() {',
        '    this.counterRef.reset(); // call child method',
        '  }',
        '}',
      ].join('\n'),
      explanation: '@ViewChild queries the component\'s view for a child component, directive, or element. It is available from ngAfterViewInit onwards. Use a template reference variable (#counter) or class type as the selector.',
    },
    {
      id: 10,
      title: 'Implement OnPush change detection with immutable update',
      code: [
        '@Component({',
        '  changeDetection: ChangeDetectionStrategy.OnPush,',
        '  template: `',
        '    <div *ngFor="let item of items; trackBy: trackById">',
        '      {{ item.name }}',
        '    </div>',
        '  `',
        '})',
        'export class ListComponent {',
        '  @Input() items: Item[] = [];',
        '',
        '  trackById = (_: number, item: Item) => item.id;',
        '}',
        '',
        '// Parent updates correctly (new array reference):',
        '// this.items = [...this.items, newItem];  // CORRECT',
        '// this.items.push(newItem);               // WRONG — mutation',
      ].join('\n'),
      explanation: 'OnPush skips change detection unless an @Input reference changes. Always pass a new array/object reference. The spread operator [...this.items, newItem] creates a new array, triggering change detection. Push mutation creates no new reference — Angular skips the update.',
    },
    {
      id: 11,
      title: 'Create a route guard using CanActivateFn',
      code: [
        'import { CanActivateFn, Router } from "@angular/router";',
        'import { inject } from "@angular/core";',
        '',
        'export const authGuard: CanActivateFn = (route, state) => {',
        '  const authService = inject(AuthService);',
        '  const router = inject(Router);',
        '',
        '  if (authService.isLoggedIn()) {',
        '    return true;',
        '  }',
        '  return router.createUrlTree(["/login"], {',
        '    queryParams: { returnUrl: state.url }',
        '  });',
        '};',
        '',
        '// Apply to route:',
        '{ path: "dashboard", component: DashboardComponent, canActivate: [authGuard] }',
      ].join('\n'),
      explanation: 'Functional guards (CanActivateFn) are the modern Angular approach — no class needed. inject() works inside the function body. Return true to allow, false to block, or a UrlTree to redirect. The returnUrl pattern preserves where the user was trying to go.',
    },
    {
      id: 12,
      title: 'Create an HTTP interceptor (functional)',
      code: [
        'import { HttpInterceptorFn } from "@angular/common/http";',
        'import { inject } from "@angular/core";',
        '',
        'export const authInterceptor: HttpInterceptorFn = (req, next) => {',
        '  const token = inject(AuthService).getToken();',
        '',
        '  const cloned = req.clone({',
        '    setHeaders: { Authorization: `Bearer ${token}` }',
        '  });',
        '',
        '  return next(cloned);',
        '};',
        '',
        '// Register in app.config.ts:',
        'provideHttpClient(withInterceptors([authInterceptor]))',
      ].join('\n'),
      explanation: 'Functional interceptors (HttpInterceptorFn) are the modern approach. req is immutable — clone it to modify. next(cloned) passes the modified request down the chain. Use inject() to access services. Register via withInterceptors() in provideHttpClient.',
    },
    {
      id: 13,
      title: 'Use RxJS switchMap for search with debounce',
      code: [
        'export class SearchComponent {',
        '  searchControl = new FormControl("");',
        '  private searchService = inject(SearchService);',
        '',
        '  results$ = this.searchControl.valueChanges.pipe(',
        '    debounceTime(300),         // wait 300ms after last keystroke',
        '    distinctUntilChanged(),    // skip if same value',
        '    filter(term => term!.length >= 2), // skip short queries',
        '    switchMap(term =>          // cancel previous request',
        '      this.searchService.search(term!).pipe(',
        '        catchError(() => of([]))',
        '      )',
        '    )',
        '  );',
        '}',
      ].join('\n'),
      explanation: 'switchMap cancels the previous inner Observable when a new value arrives — perfect for search (only the latest query matters). debounceTime prevents a request on every keystroke. distinctUntilChanged skips requests when the user types and deletes to the same value.',
    },
    {
      id: 14,
      title: 'Implement a template-driven form',
      code: [
        '@Component({',
        '  imports: [FormsModule, CommonModule],',
        '  template: `',
        '    <form #f="ngForm" (ngSubmit)="submit(f)">',
        '      <input name="email" [(ngModel)]="email"',
        '             required email #emailField="ngModel" />',
        '      <span *ngIf="emailField.invalid && emailField.touched">',
        '        Invalid email',
        '      </span>',
        '      <button [disabled]="f.invalid">Login</button>',
        '    </form>',
        '  `',
        '})',
        'export class LoginComponent {',
        '  email = "";',
        '  submit(form: NgForm) {',
        '    if (form.valid) console.log(form.value);',
        '  }',
        '}',
      ].join('\n'),
      explanation: 'Template-driven forms use ngModel for two-way binding. #f="ngForm" gives access to the form state. #emailField="ngModel" exposes the control\'s state (valid, touched, dirty). Validation state is set via HTML attributes (required, email).',
    },
    {
      id: 15,
      title: 'Use combineLatest to merge multiple streams',
      code: [
        'export class DashboardComponent {',
        '  private userService = inject(UserService);',
        '  private productService = inject(ProductService);',
        '',
        '  dashboard$ = combineLatest([',
        '    this.userService.currentUser$,',
        '    this.productService.featuredProducts$,',
        '  ]).pipe(',
        '    map(([user, products]) => ({ user, products })),',
        '    catchError(err => {',
        '      console.error(err);',
        '      return of({ user: null, products: [] });',
        '    })',
        '  );',
        '}',
      ].join('\n'),
      explanation: 'combineLatest emits an array of the latest values from all input streams whenever any stream emits. It waits until every stream has emitted at least once. Use map to reshape the combined result into a convenient object. Perfect for dashboards that need multiple data sources.',
    },
    {
      id: 16,
      title: 'Implement a signal-based counter component',
      code: [
        'import { signal, computed } from "@angular/core";',
        '',
        '@Component({',
        '  standalone: true,',
        '  template: `',
        '    <p>Count: {{ count() }}</p>',
        '    <p>Double: {{ doubled() }}</p>',
        '    <button (click)="increment()">+</button>',
        '    <button (click)="decrement()">-</button>',
        '    <button (click)="reset()">Reset</button>',
        '  `',
        '})',
        'export class CounterComponent {',
        '  count = signal(0);',
        '  doubled = computed(() => this.count() * 2);',
        '',
        '  increment() { this.count.update(v => v + 1); }',
        '  decrement() { this.count.update(v => v - 1); }',
        '  reset()     { this.count.set(0); }',
        '}',
      ].join('\n'),
      explanation: 'signal(0) creates a reactive value. computed() creates a derived signal that auto-updates when count changes. In the template, call signals as functions: count(). Angular tracks which template bindings depend on each signal for fine-grained updates.',
    },
    {
      id: 17,
      title: 'Use toSignal to convert an HTTP Observable to a Signal',
      code: [
        'import { toSignal } from "@angular/core/rxjs-interop";',
        '',
        '@Component({',
        '  standalone: true,',
        '  imports: [CommonModule],',
        '  template: `',
        '    <div *ngFor="let p of products()">{{ p.name }}</div>',
        '  `',
        '})',
        'export class ProductsComponent {',
        '  private http = inject(HttpClient);',
        '',
        '  products = toSignal(',
        '    this.http.get<Product[]>("/api/products"),',
        '    { initialValue: [] }',
        '  );',
        '}',
      ].join('\n'),
      explanation: 'toSignal() converts an Observable to a Signal. Angular auto-subscribes and auto-unsubscribes when the component is destroyed. initialValue is the value before the Observable emits. The signal updates synchronously when the Observable emits.',
    },
    {
      id: 18,
      title: 'Build a reusable table component with @Input',
      code: [
        '@Component({',
        '  selector: "app-data-table",',
        '  standalone: true,',
        '  imports: [CommonModule],',
        '  template: `',
        '    <table>',
        '      <thead><tr><th *ngFor="let col of columns">{{ col.label }}</th></tr></thead>',
        '      <tbody>',
        '        <tr *ngFor="let row of data; trackBy: trackByIndex">',
        '          <td *ngFor="let col of columns">{{ row[col.key] }}</td>',
        '        </tr>',
        '      </tbody>',
        '    </table>',
        '  `',
        '})',
        'export class DataTableComponent {',
        '  @Input() columns: { key: string; label: string }[] = [];',
        '  @Input() data: any[] = [];',
        '  trackByIndex = (i: number) => i;',
        '}',
      ].join('\n'),
      explanation: 'This generic table component accepts columns definition and data as inputs. The outer *ngFor iterates rows; the inner iterates columns. row[col.key] uses bracket notation for dynamic property access. This pattern is the foundation for reusable data grids.',
    },
    {
      id: 19,
      title: 'Implement event emission with @Output',
      code: [
        '// child.component.ts',
        '@Component({',
        '  selector: "app-product-card",',
        '  template: `',
        '    <h3>{{ product.name }}</h3>',
        '    <button (click)="addToCart()">Add to Cart</button>',
        '  `',
        '})',
        'export class ProductCardComponent {',
        '  @Input() product!: Product;',
        '  @Output() cartAdd = new EventEmitter<Product>();',
        '',
        '  addToCart() {',
        '    this.cartAdd.emit(this.product);',
        '  }',
        '}',
        '',
        '// parent template:',
        '// <app-product-card [product]="p" (cartAdd)="onAddToCart($event)" />',
      ].join('\n'),
      explanation: '@Output creates an EventEmitter that emits data to the parent. The parent listens with (cartAdd)="handler($event)". $event receives the emitted value. For Angular 17.1+, use output() signal-based API instead of @Output.',
    },
    {
      id: 20,
      title: 'Use ng-content for component projection',
      code: [
        '// card.component.ts — accepts projected content',
        '@Component({',
        '  selector: "app-card",',
        '  standalone: true,',
        '  template: `',
        '    <div class="card">',
        '      <div class="card-header">',
        '        <ng-content select="[card-title]"></ng-content>',
        '      </div>',
        '      <div class="card-body">',
        '        <ng-content></ng-content>',
        '      </div>',
        '    </div>',
        '  `',
        '})',
        'export class CardComponent {}',
        '',
        '// Usage:',
        '// <app-card>',
        '//   <h2 card-title>My Card</h2>',
        '//   <p>Card body content here</p>',
        '// </app-card>',
      ].join('\n'),
      explanation: 'ng-content is content projection (like slots in Web Components). select= attribute uses CSS selectors to target specific projected content. The default slot (no select) captures all unmatched content. Enables highly reusable wrapper components.',
    },
    {
      id: 21,
      title: 'Implement a resolver for pre-fetching route data',
      code: [
        'import { ResolveFn } from "@angular/router";',
        '',
        'export const productResolver: ResolveFn<Product> = (route) => {',
        '  const id = route.paramMap.get("id")!;',
        '  return inject(ProductService).getProduct(+id);',
        '};',
        '',
        '// Route configuration:',
        '{',
        '  path: "products/:id",',
        '  component: ProductDetailComponent,',
        '  resolve: { product: productResolver }',
        '}',
        '',
        '// In component:',
        'export class ProductDetailComponent {',
        '  product = inject(ActivatedRoute).snapshot.data["product"] as Product;',
        '}',
      ].join('\n'),
      explanation: 'Resolvers pre-fetch data before a route activates. The router waits for the Observable/Promise to complete before rendering the component. Access resolved data via ActivatedRoute.snapshot.data or ActivatedRoute.data Observable. Functional resolvers (ResolveFn) are the modern approach.',
    },
    {
      id: 22,
      title: 'Create a custom form validator',
      code: [
        'import { AbstractControl, ValidationErrors, ValidatorFn } from "@angular/forms";',
        '',
        '// Synchronous validator',
        'export function passwordStrength(): ValidatorFn {',
        '  return (control: AbstractControl): ValidationErrors | null => {',
        '    const value = control.value as string;',
        '    if (!value) return null;',
        '    const hasUpper = /[A-Z]/.test(value);',
        '    const hasNumber = /[0-9]/.test(value);',
        '    const hasSpecial = /[!@#$%]/.test(value);',
        '    const valid = hasUpper && hasNumber && hasSpecial;',
        '    return valid ? null : { weakPassword: true };',
        '  };',
        '}',
        '',
        '// Usage:',
        'password: ["", [Validators.required, passwordStrength()]]',
      ].join('\n'),
      explanation: 'A custom validator is a function returning null (valid) or an error object. ValidatorFn takes an AbstractControl and returns ValidationErrors | null. The error object key (weakPassword) is used in the template with hasError("weakPassword"). Async validators return Observable<ValidationErrors|null>.',
    },
    {
      id: 23,
      title: 'Use forkJoin for parallel HTTP requests',
      code: [
        'export class UserProfileComponent implements OnInit {',
        '  private userService = inject(UserService);',
        '  private orderService = inject(OrderService);',
        '',
        '  profile: { user: User; orders: Order[] } | null = null;',
        '',
        '  ngOnInit() {',
        '    const id = inject(ActivatedRoute).snapshot.paramMap.get("id")!;',
        '    forkJoin({',
        '      user: this.userService.getUser(id),',
        '      orders: this.orderService.getUserOrders(id)',
        '    }).subscribe(result => {',
        '      this.profile = result;',
        '    });',
        '  }',
        '}',
      ].join('\n'),
      explanation: 'forkJoin runs multiple Observables in parallel and emits once when all complete. It takes an object and preserves the keys in the result. Unlike combineLatest, forkJoin waits for all streams to complete (great for HTTP requests that complete after one emission).',
    },
    {
      id: 24,
      title: 'Implement infinite scroll with BehaviorSubject pagination',
      code: [
        'export class InfiniteListComponent {',
        '  private page$ = new BehaviorSubject<number>(1);',
        '  private productService = inject(ProductService);',
        '',
        '  products$ = this.page$.pipe(',
        '    switchMap(page => this.productService.getPage(page)),',
        '    scan((acc, page) => [...acc, ...page], [] as Product[])',
        '  );',
        '',
        '  onScroll() {',
        '    this.page$.next(this.page$.value + 1);',
        '  }',
        '}',
      ].join('\n'),
      explanation: 'BehaviorSubject holds the current page. switchMap fetches products for each page. scan accumulates pages: it receives the accumulated array and appends new items, like Array.reduce but for streams. Call onScroll() when the user reaches the bottom (e.g., via IntersectionObserver).',
    },
    {
      id: 25,
      title: 'Create a loading/error wrapper with async pipe',
      code: [
        '@Component({',
        '  imports: [CommonModule],',
        '  template: `',
        '    <ng-container *ngIf="vm$ | async as vm">',
        '      <app-spinner *ngIf="vm.loading"></app-spinner>',
        '      <p class="error" *ngIf="vm.error">{{ vm.error }}</p>',
        '      <app-product-list *ngIf="vm.data" [products]="vm.data" />',
        '    </ng-container>',
        '  `',
        '})',
        'export class ProductPageComponent {',
        '  vm$ = inject(ProductService).getProducts().pipe(',
        '    map(data => ({ loading: false, data, error: null })),',
        '    startWith({ loading: true, data: null, error: null }),',
        '    catchError(e => of({ loading: false, data: null, error: e.message }))',
        '  );',
        '}',
      ].join('\n'),
      explanation: 'The ViewModel pattern wraps loading, data, and error states in a single Observable. startWith emits the loading state before the HTTP request completes. catchError transforms errors into the same VM shape. async pipe handles subscription and unsubscription automatically.',
    },
    {
      id: 26,
      title: 'Use HostListener and HostBinding in a directive',
      code: [
        '@Directive({ selector: "[appHoverHighlight]", standalone: true })',
        'export class HoverHighlightDirective {',
        '  @HostBinding("style.backgroundColor") bgColor = "transparent";',
        '  @HostBinding("style.cursor") cursor = "pointer";',
        '',
        '  @HostListener("mouseenter") onEnter() {',
        '    this.bgColor = "#e0f2fe";',
        '  }',
        '',
        '  @HostListener("mouseleave") onLeave() {',
        '    this.bgColor = "transparent";',
        '  }',
        '}',
        '',
        '// Usage: <div appHoverHighlight>Hover me!</div>',
      ].join('\n'),
      explanation: '@HostBinding binds a directive property to a host element attribute or style. @HostListener subscribes to host element DOM events. No need for ElementRef in this pattern. This creates a purely declarative directive with no direct DOM manipulation.',
    },
    {
      id: 27,
      title: 'Implement a retry strategy for failed HTTP requests',
      code: [
        'export class ApiService {',
        '  private http = inject(HttpClient);',
        '',
        '  fetchWithRetry<T>(url: string): Observable<T> {',
        '    return this.http.get<T>(url).pipe(',
        '      retryWhen(errors => errors.pipe(',
        '        scan((count, err) => {',
        '          if (count >= 3) throw err;',
        '          return count + 1;',
        '        }, 0),',
        '        delay(1000)',
        '      ))',
        '    );',
        '  }',
        '',
        '  // Modern approach with retry():',
        '  fetchModern<T>(url: string): Observable<T> {',
        '    return this.http.get<T>(url).pipe(',
        '      retry({ count: 3, delay: 1000 })',
        '    );',
        '  }',
        '}',
      ].join('\n'),
      explanation: 'retry({ count, delay }) is the modern RxJS 7+ approach. It retries the source Observable up to count times with delay milliseconds between attempts. retryWhen (deprecated) allows more complex retry logic using scan to count attempts. Always cap retries to avoid infinite loops.',
    },
    {
      id: 28,
      title: 'Create a shared state service with BehaviorSubject',
      code: [
        '@Injectable({ providedIn: "root" })',
        'export class CartService {',
        '  private _items$ = new BehaviorSubject<CartItem[]>([]);',
        '',
        '  // Expose as read-only Observable',
        '  items$ = this._items$.asObservable();',
        '  count$ = this.items$.pipe(map(items => items.length));',
        '  total$ = this.items$.pipe(',
        '    map(items => items.reduce((sum, i) => sum + i.price * i.qty, 0))',
        '  );',
        '',
        '  addItem(item: CartItem) {',
        '    this._items$.next([...this._items$.value, item]);',
        '  }',
        '',
        '  removeItem(id: string) {',
        '    this._items$.next(this._items$.value.filter(i => i.id !== id));',
        '  }',
        '}',
      ].join('\n'),
      explanation: 'BehaviorSubject holds the current state and emits to new subscribers immediately. Expose it as asObservable() to prevent external code from calling next() directly. Derived streams (count$, total$) are computed from items$ using pipe/map — single source of truth.',
    },
    {
      id: 29,
      title: 'Implement a debounced window resize listener',
      code: [
        '@Component({ ... })',
        'export class ResponsiveComponent implements OnInit, OnDestroy {',
        '  isMobile = false;',
        '  private destroy$ = new Subject<void>();',
        '',
        '  ngOnInit() {',
        '    fromEvent(window, "resize").pipe(',
        '      debounceTime(200),',
        '      map(() => window.innerWidth < 768),',
        '      distinctUntilChanged(),',
        '      takeUntil(this.destroy$)',
        '    ).subscribe(mobile => {',
        '      this.isMobile = mobile;',
        '    });',
        '  }',
        '',
        '  ngOnDestroy() {',
        '    this.destroy$.next();',
        '    this.destroy$.complete();',
        '  }',
        '}',
      ].join('\n'),
      explanation: 'fromEvent creates an Observable from a DOM event. debounceTime prevents excessive calculations during rapid resize. distinctUntilChanged prevents re-renders when the breakpoint does not change. takeUntil + destroy$ subject is the classic unsubscription pattern (use takeUntilDestroyed() in Angular 16+).',
    },
    {
      id: 30,
      title: 'Use @ContentChild to access projected content',
      code: [
        '@Component({',
        '  selector: "app-accordion",',
        '  template: `',
        '    <div class="accordion">',
        '      <ng-content></ng-content>',
        '    </div>',
        '  `',
        '})',
        'export class AccordionComponent implements AfterContentInit {',
        '  @ContentChild(AccordionHeaderComponent)',
        '  header!: AccordionHeaderComponent;',
        '',
        '  ngAfterContentInit() {',
        '    // header is available here — it is projected content',
        '    this.header.expanded$.subscribe(v => console.log(v));',
        '  }',
        '}',
      ].join('\n'),
      explanation: '@ContentChild queries content projected via ng-content. It is available from ngAfterContentInit onwards. @ContentChildren gets all matching projected children as a QueryList. Use when building compound components (accordion + accordion-item, tab + tab-panel).',
    },
    {
      id: 31,
      title: 'Implement route parameter reading',
      code: [
        'export class ProductDetailComponent {',
        '  private route = inject(ActivatedRoute);',
        '  private productService = inject(ProductService);',
        '',
        '  // Snapshot — for static route (will not update if param changes while open)',
        '  productId = this.route.snapshot.paramMap.get("id");',
        '',
        '  // Observable — reactive to param changes',
        '  product$ = this.route.paramMap.pipe(',
        '    map(params => params.get("id")!),',
        '    switchMap(id => this.productService.getProduct(id))',
        '  );',
        '}',
      ].join('\n'),
      explanation: 'Use paramMap Observable (not snapshot) when the same component can be reused with different params (same route, different id). switchMap cancels the previous HTTP request when the id changes. snapshot.paramMap.get() is fine when the component is always destroyed and recreated on navigation.',
    },
    {
      id: 32,
      title: 'Create a pipe that formats bytes to human-readable size',
      code: [
        '@Pipe({ name: "fileSize", standalone: true })',
        'export class FileSizePipe implements PipeTransform {',
        '  private units = ["B", "KB", "MB", "GB", "TB"];',
        '',
        '  transform(bytes: number, decimals = 2): string {',
        '    if (bytes === 0) return "0 B";',
        '    const k = 1024;',
        '    const i = Math.floor(Math.log(bytes) / Math.log(k));',
        '    return parseFloat((bytes / Math.pow(k, i)).toFixed(decimals))',
        '           + " " + this.units[i];',
        '  }',
        '}',
        '',
        '// Usage: {{ file.size | fileSize }} → "2.34 MB"',
        '//        {{ file.size | fileSize:0 }} → "2 MB"',
      ].join('\n'),
      explanation: 'Math.log(bytes)/Math.log(1024) calculates which unit tier (B, KB, MB…) to use. Math.floor gives the integer index. This is a pure pipe — it recalculates only when the input value changes, not on every change detection cycle (default for custom pipes).',
    },
    {
      id: 33,
      title: 'Implement NgRx basic store with action, reducer, selector',
      code: [
        '// counter.actions.ts',
        'export const increment = createAction("[Counter] Increment");',
        'export const decrement = createAction("[Counter] Decrement");',
        '',
        '// counter.reducer.ts',
        'export const counterReducer = createReducer(',
        '  0,',
        '  on(increment, state => state + 1),',
        '  on(decrement, state => state - 1)',
        ');',
        '',
        '// counter.selectors.ts',
        'export const selectCount = (state: AppState) => state.counter;',
        '',
        '// component.ts',
        'export class CounterComponent {',
        '  count$ = inject(Store).select(selectCount);',
        '  increment() { inject(Store).dispatch(increment()); }',
        '}',
      ].join('\n'),
      explanation: 'NgRx follows Redux pattern: actions describe events, reducers transform state, selectors derive data. createReducer with on() handlers is the modern approach. The Store is injected and used to select state or dispatch actions. State is immutable — reducers return new state.',
    },
    {
      id: 34,
      title: 'Build a multi-step form with FormGroup nesting',
      code: [
        'export class RegistrationComponent {',
        '  private fb = inject(FormBuilder);',
        '',
        '  form = this.fb.group({',
        '    personal: this.fb.group({',
        '      firstName: ["", Validators.required],',
        '      lastName: ["", Validators.required]',
        '    }),',
        '    contact: this.fb.group({',
        '      email: ["", [Validators.required, Validators.email]],',
        '      phone: [""]',
        '    }),',
        '    account: this.fb.group({',
        '      username: ["", Validators.required],',
        '      password: ["", [Validators.required, Validators.minLength(8)]]',
        '    })',
        '  });',
        '',
        '  get personalGroup() { return this.form.get("personal") as FormGroup; }',
        '}',
      ].join('\n'),
      explanation: 'Nested FormGroups organize complex forms into sections. Each sub-group is validated independently. In the template, use [formGroup]="form" on the outer form and formGroupName="personal" for nested groups. This enables step-by-step validation per section.',
    },
    {
      id: 35,
      title: 'Create a dynamic FormArray for repeating fields',
      code: [
        'export class SkillsFormComponent {',
        '  private fb = inject(FormBuilder);',
        '',
        '  form = this.fb.group({',
        '    skills: this.fb.array([this.createSkill()])',
        '  });',
        '',
        '  get skills() { return this.form.get("skills") as FormArray; }',
        '',
        '  createSkill() {',
        '    return this.fb.group({',
        '      name: ["", Validators.required],',
        '      level: ["beginner"]',
        '    });',
        '  }',
        '',
        '  addSkill()      { this.skills.push(this.createSkill()); }',
        '  removeSkill(i)  { this.skills.removeAt(i); }',
        '}',
        '',
        '// Template: [formArrayName]="\'skills\'" + formGroupName="i"',
      ].join('\n'),
      explanation: 'FormArray manages dynamic lists of form controls. push() adds controls; removeAt(i) removes them. In the template, use formArrayName="skills" on the container and *ngFor="let s of skills.controls; let i=index" with formGroupName="{{ i }}" on each item.',
    },
    {
      id: 36,
      title: 'Implement an async validator for username availability',
      code: [
        'export function usernameAvailable(userService: UserService): AsyncValidatorFn {',
        '  return (control: AbstractControl): Observable<ValidationErrors | null> => {',
        '    if (!control.value) return of(null);',
        '    return timer(400).pipe(  // debounce built-in to async validator',
        '      switchMap(() => userService.checkUsername(control.value)),',
        '      map(available => available ? null : { usernameTaken: true }),',
        '      catchError(() => of(null))  // on error: assume valid',
        '    );',
        '  };',
        '}',
        '',
        '// Usage:',
        'username: ["", Validators.required, usernameAvailable(inject(UserService))]',
      ].join('\n'),
      explanation: 'AsyncValidatorFn returns Observable<ValidationErrors|null>. Use timer(400) to debounce the API call — Angular does not debounce async validators automatically. switchMap cancels previous requests. The third argument to FormControl is async validators (not the second).',
    },
    {
      id: 37,
      title: 'Use the inject() function instead of constructor injection',
      code: [
        '// Modern Angular — inject() in field declarations',
        '@Component({ ... })',
        'export class ProductComponent {',
        '  private productService = inject(ProductService);',
        '  private route         = inject(ActivatedRoute);',
        '  private router        = inject(Router);',
        '  private store         = inject(Store);',
        '',
        '  products$ = this.productService.getAll();',
        '  routeId   = this.route.snapshot.paramMap.get("id");',
        '',
        '  navigate() { this.router.navigate(["/home"]); }',
        '}',
        '',
        '// inject() also works in standalone functions (guards, interceptors)',
        'export const authGuard: CanActivateFn = () => inject(AuthService).isLoggedIn();',
      ].join('\n'),
      explanation: 'inject() is the modern dependency injection function available in Angular 14+. It must be called in an injection context (component field initializer, constructor, or factory function). It reduces constructor boilerplate and works in standalone functions like guards and interceptors.',
    },
    {
      id: 38,
      title: 'Implement takeUntilDestroyed for auto unsubscription',
      code: [
        'import { takeUntilDestroyed } from "@angular/core/rxjs-interop";',
        '',
        '@Component({ ... })',
        'export class DashboardComponent {',
        '  private destroyRef = inject(DestroyRef);',
        '',
        '  constructor() {',
        '    this.dataService.realTimeUpdates$.pipe(',
        '      takeUntilDestroyed(this.destroyRef)',
        '    ).subscribe(data => {',
        '      this.latestData = data;',
        '    });',
        '  }',
        '}',
        '',
        '// Even simpler — inject DestroyRef automatically:',
        '// takeUntilDestroyed() without arguments works in injection context',
      ].join('\n'),
      explanation: 'takeUntilDestroyed() (Angular 16+) automatically completes subscriptions when the component is destroyed. It replaces the manual destroy$ Subject pattern. Pass DestroyRef explicitly if used outside the constructor/field initializer. Works with any injectable context.',
    },
    {
      id: 39,
      title: 'Create a breadcrumb component reading route data',
      code: [
        '@Component({',
        '  selector: "app-breadcrumb",',
        '  standalone: true,',
        '  imports: [CommonModule, RouterModule],',
        '  template: `',
        '    <nav>',
        '      <a *ngFor="let crumb of breadcrumbs$ | async; let last = last"',
        '         [routerLink]="crumb.url"',
        '         [class.active]="last">',
        '        {{ crumb.label }}',
        '      </a>',
        '    </nav>',
        '  `',
        '})',
        'export class BreadcrumbComponent {',
        '  breadcrumbs$ = inject(Router).events.pipe(',
        '    filter(e => e instanceof NavigationEnd),',
        '    map(() => this.buildBreadcrumbs(inject(ActivatedRoute).root))',
        '  );',
        '}',
      ].join('\n'),
      explanation: 'Router.events Observable emits all router events. Filter for NavigationEnd to rebuild breadcrumbs after each navigation. Traverse the ActivatedRoute tree from root, collecting route data.breadcrumb labels. This auto-updates on every navigation.',
    },
    {
      id: 40,
      title: 'Use the Renderer2 for safe DOM manipulation',
      code: [
        '@Directive({ selector: "[appAutoFocus]", standalone: true })',
        'export class AutoFocusDirective implements AfterViewInit {',
        '  private el = inject(ElementRef);',
        '  private renderer = inject(Renderer2);',
        '',
        '  ngAfterViewInit() {',
        '    this.renderer.selectRootElement(this.el.nativeElement).focus();',
        '  }',
        '}',
        '',
        '// Or for adding a class:',
        'this.renderer.addClass(this.el.nativeElement, "focused");',
        'this.renderer.setStyle(this.el.nativeElement, "color", "red");',
        'this.renderer.setAttribute(this.el.nativeElement, "aria-label", "...");',
      ].join('\n'),
      explanation: 'Renderer2 is the Angular abstraction over DOM operations. Use it instead of direct nativeElement manipulation for server-side rendering (SSR) compatibility and security. It works in Web Workers and non-browser environments where the DOM API is not available.',
    },
    {
      id: 41,
      title: 'Build a pagination component with @Input/@Output',
      code: [
        '@Component({',
        '  selector: "app-pagination",',
        '  standalone: true,',
        '  imports: [CommonModule],',
        '  template: `',
        '    <button (click)="changePage(currentPage - 1)" [disabled]="currentPage === 1">Prev</button>',
        '    <span>{{ currentPage }} / {{ totalPages }}</span>',
        '    <button (click)="changePage(currentPage + 1)" [disabled]="currentPage === totalPages">Next</button>',
        '  `',
        '})',
        'export class PaginationComponent {',
        '  @Input() currentPage = 1;',
        '  @Input() totalPages = 1;',
        '  @Output() pageChange = new EventEmitter<number>();',
        '',
        '  changePage(page: number) {',
        '    if (page >= 1 && page <= this.totalPages) {',
        '      this.pageChange.emit(page);',
        '    }',
        '  }',
        '}',
      ].join('\n'),
      explanation: 'This is a controlled (presentational) component — it receives state via @Input and reports changes via @Output. The parent manages the actual page state. [disabled] prevents navigating past boundaries. This pattern keeps the component logic-free and highly reusable.',
    },
    {
      id: 42,
      title: 'Implement a notification service with Subject',
      code: [
        '@Injectable({ providedIn: "root" })',
        'export class NotificationService {',
        '  private notify$ = new Subject<Notification>();',
        '  notifications$ = this.notify$.asObservable();',
        '',
        '  success(message: string) {',
        '    this.notify$.next({ type: "success", message });',
        '  }',
        '',
        '  error(message: string) {',
        '    this.notify$.next({ type: "error", message });',
        '  }',
        '}',
        '',
        '// Toast component subscribes and displays each notification',
        'export class ToastComponent {',
        '  messages$ = inject(NotificationService).notifications$;',
        '}',
      ].join('\n'),
      explanation: 'Subject (not BehaviorSubject) is used here because notifications are events, not state — new subscribers should not see past notifications. asObservable() hides the next() method from consumers. The toast component subscribes and auto-displays messages.',
    },
    {
      id: 43,
      title: 'Create an attribute directive for input formatting',
      code: [
        '@Directive({',
        '  selector: "input[appPhoneFormat]",',
        '  standalone: true,',
        '  host: { "(input)": "onInput($event)" }',
        '})',
        'export class PhoneFormatDirective {',
        '  private el = inject(ElementRef);',
        '',
        '  onInput(event: Event) {',
        '    const input = event.target as HTMLInputElement;',
        '    let value = input.value.replace(/\\D/g, "");',
        '    if (value.length > 3 && value.length <= 6) {',
        '      value = value.slice(0, 3) + "-" + value.slice(3);',
        '    } else if (value.length > 6) {',
        '      value = value.slice(0,3) + "-" + value.slice(3,6) + "-" + value.slice(6,10);',
        '    }',
        '    this.el.nativeElement.value = value;',
        '  }',
        '}',
      ].join('\n'),
      explanation: 'Attribute directives enhance existing elements without changing their structure. The selector "input[appPhoneFormat]" targets only input elements with the directive. host object is a modern alternative to @HostListener. Manipulating nativeElement.value directly bypasses Angular forms — use ControlValueAccessor for reactive forms integration.',
    },
    {
      id: 44,
      title: 'Use APP_INITIALIZER to load config before bootstrap',
      code: [
        'export function initializeApp(configService: ConfigService) {',
        '  return () => configService.loadConfig();',
        '}',
        '',
        '// app.config.ts',
        'export const appConfig: ApplicationConfig = {',
        '  providers: [',
        '    {',
        '      provide: APP_INITIALIZER,',
        '      useFactory: initializeApp,',
        '      deps: [ConfigService],',
        '      multi: true',
        '    }',
        '  ]',
        '};',
        '',
        '// ConfigService.loadConfig() returns Promise<void>',
        '// Angular waits for it to resolve before rendering the app',
      ].join('\n'),
      explanation: 'APP_INITIALIZER runs before the app renders. multi: true allows multiple initializers. Return a Promise or Observable from the factory function — Angular waits for all to complete. Use it to load environment config, translations (i18n), or feature flags from a remote API before the first render.',
    },
    {
      id: 45,
      title: 'Implement component communication via a shared service',
      code: [
        '@Injectable({ providedIn: "root" })',
        'export class SidebarService {',
        '  private isOpen$ = new BehaviorSubject(false);',
        '  open$ = this.isOpen$.asObservable();',
        '',
        '  open()  { this.isOpen$.next(true); }',
        '  close() { this.isOpen$.next(false); }',
        '  toggle() { this.isOpen$.next(!this.isOpen$.value); }',
        '}',
        '',
        '// Header component (unrelated in DOM tree)',
        'openSidebar() { inject(SidebarService).open(); }',
        '',
        '// Sidebar component',
        'isOpen$ = inject(SidebarService).open$;',
      ].join('\n'),
      explanation: 'Shared services are the best pattern for sibling or distant component communication. BehaviorSubject holds the current state, allowing late subscribers to get the current value immediately. This avoids deeply nested @Output chains or NgRx for simple UI state.',
    },
    {
      id: 46,
      title: 'Create a generic confirm dialog using service + dynamic component',
      code: [
        '@Injectable({ providedIn: "root" })',
        'export class DialogService {',
        '  private vcr!: ViewContainerRef;',
        '',
        '  setViewContainerRef(vcr: ViewContainerRef) { this.vcr = vcr; }',
        '',
        '  confirm(message: string): Promise<boolean> {',
        '    return new Promise(resolve => {',
        '      const ref = this.vcr.createComponent(ConfirmDialogComponent);',
        '      ref.instance.message = message;',
        '      ref.instance.confirmed.subscribe((result: boolean) => {',
        '        ref.destroy();',
        '        resolve(result);',
        '      });',
        '    });',
        '  }',
        '}',
        '',
        '// Usage: const ok = await dialogService.confirm("Delete item?");',
      ].join('\n'),
      explanation: 'ViewContainerRef.createComponent() dynamically creates a component at runtime — no template needed. The created component instance can have its properties set directly. Destroying the ref removes the component from the DOM. This pattern powers modal dialogs, toast notifications, and tooltips.',
    },
    {
      id: 47,
      title: 'Implement canDeactivate guard to prevent unsaved changes',
      code: [
        'export interface CanComponentDeactivate {',
        '  canDeactivate: () => boolean | Observable<boolean>;',
        '}',
        '',
        'export const unsavedChangesGuard: CanDeactivateFn<CanComponentDeactivate> =',
        '  (component) => {',
        '    if (!component.canDeactivate || component.canDeactivate()) {',
        '      return true;',
        '    }',
        '    return confirm("You have unsaved changes. Leave anyway?");',
        '  };',
        '',
        '// In form component:',
        'canDeactivate() {',
        '  return !this.form.dirty;',
        '}',
      ].join('\n'),
      explanation: 'CanDeactivate prevents navigation away from a component (e.g., unsaved form). The component implements an interface with canDeactivate() returning boolean/Observable. The functional guard calls it and can use confirm() or return an Observable from a dialog for async confirmation.',
    },
    {
      id: 48,
      title: 'Build a search filter pipe',
      code: [
        '@Pipe({ name: "searchFilter", standalone: true })',
        'export class SearchFilterPipe implements PipeTransform {',
        '  transform(items: any[], searchTerm: string, field: string): any[] {',
        '    if (!items || !searchTerm) return items;',
        '    const term = searchTerm.toLowerCase();',
        '    return items.filter(item =>',
        '      String(item[field]).toLowerCase().includes(term)',
        '    );',
        '  }',
        '}',
        '',
        '// Usage:',
        '// <div *ngFor="let p of products | searchFilter:searchTerm:\'name\'">',
        '// Note: For large lists, filter in the component for performance',
      ].join('\n'),
      explanation: 'The pipe takes items, a search term, and the field to search. String(item[field]) handles non-string values. Impure pipes (pure: false) would update on every CD cycle — keep this pure. For large datasets, move filtering to the component using BehaviorSubject and RxJS operators for better performance.',
    },
    {
      id: 49,
      title: 'Implement a color-theme toggle with CSS custom properties',
      code: [
        '@Injectable({ providedIn: "root" })',
        'export class ThemeService {',
        '  private isDark$ = new BehaviorSubject<boolean>(false);',
        '  theme$ = this.isDark$.asObservable();',
        '',
        '  toggle() {',
        '    const dark = !this.isDark$.value;',
        '    this.isDark$.next(dark);',
        '    document.documentElement.classList.toggle("dark-theme", dark);',
        '    localStorage.setItem("theme", dark ? "dark" : "light");',
        '  }',
        '',
        '  init() {',
        '    const saved = localStorage.getItem("theme") === "dark";',
        '    this.isDark$.next(saved);',
        '    document.documentElement.classList.toggle("dark-theme", saved);',
        '  }',
        '}',
        '',
        '// CSS: :root.dark-theme { --bg: #1a1a2e; --text: #eee; }',
      ].join('\n'),
      explanation: 'CSS custom properties (variables) enable runtime theme switching without JavaScript style manipulation. Adding a class to document.documentElement switches all components that use CSS variables. localStorage persists the preference. Call init() in APP_INITIALIZER to apply the saved theme before first render.',
    },
    {
      id: 50,
      title: 'Write a unit test for an Angular component',
      code: [
        'describe("CounterComponent", () => {',
        '  let component: CounterComponent;',
        '  let fixture: ComponentFixture<CounterComponent>;',
        '',
        '  beforeEach(async () => {',
        '    await TestBed.configureTestingModule({',
        '      imports: [CounterComponent]  // standalone: import directly',
        '    }).compileComponents();',
        '',
        '    fixture = TestBed.createComponent(CounterComponent);',
        '    component = fixture.componentInstance;',
        '    fixture.detectChanges();',
        '  });',
        '',
        '  it("should start at 0", () => {',
        '    expect(component.count()).toBe(0);',
        '  });',
        '',
        '  it("should increment on button click", () => {',
        '    const btn = fixture.nativeElement.querySelector("button");',
        '    btn.click();',
        '    fixture.detectChanges();',
        '    expect(component.count()).toBe(1);',
        '  });',
        '});',
      ].join('\n'),
      explanation: 'TestBed creates an Angular testing environment. Standalone components are imported (not declared). fixture.detectChanges() triggers change detection. Test the component via component instance properties or the rendered nativeElement. For services, use TestBed.inject(MyService) or provide mocks via { provide: MyService, useValue: mockService }.',
    },
  ];
}
