import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-http-interceptor',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './http-interceptor.component.html',
  styleUrl: './http-interceptor.component.css',
})
export class HttpInterceptorTopicComponent {
  syntaxCode = [
    '// ── Class-based Interceptor (Angular < 15) ──────────────────',
    'import { Injectable } from "@angular/core";',
    'import {',
    '  HttpInterceptor, HttpRequest, HttpHandler,',
    '  HttpEvent, HttpResponse',
    '} from "@angular/common/http";',
    'import { Observable, tap } from "rxjs";',
    '',
    '@Injectable()',
    'export class LoggingInterceptor implements HttpInterceptor {',
    '  intercept(req: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {',
    '    console.log("Outgoing request:", req.method, req.url);',
    '    return next.handle(req).pipe(',
    '      tap(event => {',
    '        if (event instanceof HttpResponse) {',
    '          console.log("Response status:", event.status);',
    '        }',
    '      })',
    '    );',
    '  }',
    '}',
    '',
    '// ── Functional Interceptor (Angular 15+) ─────────────────────',
    'import { HttpInterceptorFn } from "@angular/common/http";',
    '',
    'export const loggingInterceptor: HttpInterceptorFn = (req, next) => {',
    '  console.log("Request:", req.method, req.url);',
    '  return next(req).pipe(',
    '    tap(event => {',
    '      if (event instanceof HttpResponse) {',
    '        console.log("Response:", event.status);',
    '      }',
    '    })',
    '  );',
    '};',
    '',
    '// ── Registering (Angular 15+ standalone) ─────────────────────',
    '// In bootstrapApplication:',
    '// provideHttpClient(withInterceptors([loggingInterceptor, authInterceptor]))',
  ].join('\n');

  exampleCode = [
    '// Real-world: Full logging + timing interceptor',
    '',
    'export const requestTimingInterceptor: HttpInterceptorFn = (req, next) => {',
    '  const start = Date.now();',
    '  const reqId = Math.random().toString(36).substr(2, 9);',
    '',
    '  console.log(`[${reqId}] --> ${req.method} ${req.url}`);',
    '',
    '  // Clone request to add custom header (requests are immutable)',
    '  const cloned = req.clone({',
    '    headers: req.headers',
    '      .set("X-Request-Id", reqId)',
    '      .set("X-Client-Version", "1.0.0")',
    '  });',
    '',
    '  return next(cloned).pipe(',
    '    tap({',
    '      next: (event) => {',
    '        if (event instanceof HttpResponse) {',
    '          const elapsed = Date.now() - start;',
    '          console.log(`[${reqId}] <-- ${event.status} (${elapsed}ms)`);',
    '        }',
    '      },',
    '      error: (err) => {',
    '        const elapsed = Date.now() - start;',
    '        console.error(`[${reqId}] ERROR ${err.status} (${elapsed}ms)`);',
    '      }',
    '    })',
    '  );',
    '};',
    '',
    '// Multiple interceptors run in order (like middleware):',
    '// provideHttpClient(withInterceptors([',
    '//   requestTimingInterceptor,  // runs first',
    '//   authInterceptor,           // runs second',
    '//   errorInterceptor           // runs third',
    '// ]))',
  ].join('\n');

  interviewQA = [
    {
      q: 'What is an Angular HTTP Interceptor and what problem does it solve?',
      a: 'An Angular HTTP Interceptor is middleware that sits in the HTTP pipeline and intercepts every HttpClient request and response. It solves the cross-cutting concern problem — instead of adding authentication headers, logging, or error handling in every service method, you write it once in an interceptor and it applies automatically to all HTTP calls. Common use cases: adding Authorization headers, logging, showing loading spinners, caching, error handling, request retrying, and response transformation.',
    },
    {
      q: 'What is the difference between class-based and functional interceptors in Angular?',
      a: 'Class-based interceptors (pre-Angular 15) implement the HttpInterceptor interface with an intercept(req, next) method and are registered using HTTP_INTERCEPTORS multi-provider token. Functional interceptors (Angular 15+) are plain functions matching the HttpInterceptorFn type signature and are registered via provideHttpClient(withInterceptors([fn1, fn2])). Functional interceptors are simpler (no class boilerplate), work naturally with inject() for DI, are tree-shakable, and are the Angular team\'s recommended approach for modern apps.',
    },
    {
      q: 'Why must you clone the HttpRequest before modifying it?',
      a: 'HttpRequest objects in Angular are immutable — you cannot modify them directly. Attempting to set headers on the original request will not work. The req.clone({ headers: ... }) method creates a new HttpRequest with the specified modifications while copying all other properties. This immutability is intentional: it ensures that interceptors are composable and that no interceptor can accidentally corrupt the request for subsequent interceptors in the chain. Always use req.clone() and pass the cloned request to next.handle(cloned) / next(cloned).',
    },
    {
      q: 'In what order do interceptors run and how does the chain work?',
      a: 'Interceptors run in the order they are registered — like middleware. For outgoing requests: interceptor 1 → interceptor 2 → interceptor 3 → HttpBackend (actual HTTP call). For incoming responses, the pipe() operators in each interceptor run in reverse: interceptor 3\'s tap → interceptor 2\'s tap → interceptor 1\'s tap. This mirrors Express.js middleware behavior. In withInterceptors([a, b, c]), interceptor a runs first on the way out and last on the way back.',
    },
    {
      q: 'How do you skip an interceptor for specific requests (e.g., skip auth for /login)?',
      a: 'Several approaches: (1) Check request URL in the interceptor: if (req.url.includes("/login")) return next(req); (2) Use HttpContext — pass a token in request options: req.clone({ context: new HttpContext().set(SKIP_AUTH, true) }) and check in the interceptor: if (req.context.get(SKIP_AUTH)) return next(req); (3) Check if the request has certain headers. The HttpContext approach (Angular 12+) is the cleanest — it avoids URL string matching which breaks with different environments.',
    },
    {
      q: 'What is the difference between tap() and map() in interceptor response handling?',
      a: 'tap() is a side-effect operator — it lets you observe the response (logging, showing notifications) without transforming it. The response continues downstream unchanged. map() transforms the response — useful for unwrapping API envelopes (extracting data from { status, data: {...} }). Example: tap(event => logEvent(event)) vs map(event => event instanceof HttpResponse ? event.clone({ body: event.body.data }) : event). Use tap for side effects, map for response transformation.',
    },
    {
      q: 'How do you inject a service into a functional interceptor?',
      a: 'Use the inject() function (Angular 14+) inside the functional interceptor body: export const authInterceptor: HttpInterceptorFn = (req, next) => { const authService = inject(AuthService); const token = authService.getToken(); ... }. The inject() function works in injection context — and functional interceptors run in injection context automatically. For class-based interceptors, inject services via the constructor as usual. This is one of the key advantages of functional interceptors — no need for a constructor.',
    },
  ];
}
