import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-form-group',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './form-group.component.html',
  styleUrl: './form-group.component.css',
})
export class FormGroupComponent {
  syntaxCode = [
    'import { FormGroup, FormControl, Validators } from "@angular/forms";',
    '',
    '// Create a FormGroup with FormControl children',
    'const form = new FormGroup({',
    '  name:  new FormControl("", Validators.required),',
    '  email: new FormControl("", [Validators.required, Validators.email]),',
    '',
    '  // Nested FormGroup',
    '  address: new FormGroup({',
    '    street: new FormControl(""),',
    '    city:   new FormControl("", Validators.required),',
    '    zip:    new FormControl(""),',
    '  }),',
    '});',
    '',
    '// Access nested control with dot-path string',
    'form.get("address.city")?.value;',
    'form.get("address.city")?.errors;',
    '',
    '// setValue — ALL fields required',
    'form.setValue({',
    '  name: "Alice", email: "alice@example.com",',
    '  address: { street: "123 Main St", city: "Austin", zip: "78701" },',
    '});',
    '',
    '// patchValue — partial update, rest unchanged',
    'form.patchValue({ name: "Bob" });',
    '',
    '// Reset value and state flags',
    'form.reset();',
    '',
    '// Aggregate state checks',
    'form.valid;   // true only when ALL controls pass validation',
    'form.dirty;   // true when any control value has changed',
    'form.touched; // true when any control has been blurred',
  ].join('\n');

  exampleCode = [
    '// user-profile.component.ts',
    'export class UserProfileComponent implements OnInit {',
    '  form!: FormGroup;',
    '',
    '  constructor(private fb: FormBuilder) {}',
    '',
    '  ngOnInit() {',
    '    this.form = this.fb.group({',
    '      name:  ["", Validators.required],',
    '      email: ["", [Validators.required, Validators.email]],',
    '',
    '      // Nested FormGroup for address',
    '      address: this.fb.group({',
    '        street: [""],',
    '        city:   ["", Validators.required],',
    '        zip:    ["", Validators.pattern(/^\\d{5}$/)],',
    '      }, { validators: this.cityZipValidator }),  // group-level validator',
    '    });',
    '  }',
    '',
    '  // Group-level cross-field validator',
    '  cityZipValidator(group: AbstractControl) {',
    '    const city = group.get("city")?.value;',
    '    const zip  = group.get("zip")?.value;',
    '    return city && !zip ? { zipRequired: true } : null;',
    '  }',
    '',
    '  // Access nested control via dot-path',
    '  get city() { return this.form.get("address.city"); }',
    '',
    '  // Partially update only what changed',
    '  loadCity() {',
    '    this.form.patchValue({ address: { city: "Austin" } });',
    '  }',
    '',
    '  onSave() {',
    '    if (this.form.valid) {',
    '      console.log(this.form.value);',
    '      // { name: "Alice", email: "...", address: { street: "...", city: "Austin", zip: "78701" } }',
    '    }',
    '  }',
    '}',
    '',
    '<!-- user-profile.component.html -->',
    '<form [formGroup]="form" (ngSubmit)="onSave()">',
    '  <input formControlName="name" placeholder="Name" />',
    '  <input formControlName="email" placeholder="Email" />',
    '',
    '  <div formGroupName="address">',
    '    <input formControlName="street" placeholder="Street" />',
    '    <input formControlName="city"   placeholder="City" />',
    '    <input formControlName="zip"    placeholder="ZIP" />',
    '  </div>',
    '',
    '  <button type="submit" [disabled]="form.invalid">Save</button>',
    '</form>',
  ].join('\n');

  interviewQA = [
    {
      q: 'What is FormGroup in Angular Reactive Forms?',
      a: 'FormGroup is a collection of AbstractControl instances (FormControl, nested FormGroup, or FormArray) keyed by name. It tracks the combined value and validity of all its children. A FormGroup is invalid if any child control is invalid. It is the standard way to model a form or a sub-section of a form in TypeScript.',
    },
    {
      q: 'How do nested FormGroups work and how do you access a nested control?',
      a: 'A FormGroup can contain another FormGroup as a child, enabling hierarchical form structures (e.g. an address group inside a profile group). In the template, bind the parent with [formGroup]="form" and the nested group with formGroupName="address". In TypeScript, access a nested control with the dot-path string: form.get("address.city") — Angular traverses the path automatically.',
    },
    {
      q: 'What is the difference between setValue and patchValue on a FormGroup?',
      a: 'setValue requires you to provide values for every control in the FormGroup (and nested groups); omitting any key throws an error. patchValue accepts a partial object and only updates the supplied keys, leaving unspecified controls untouched. Use setValue when you have a complete data object; use patchValue for partial pre-fills or incremental updates.',
    },
    {
      q: 'What does FormGroup\'s status property represent and what are the possible values?',
      a: 'FormGroup.status is a string indicating the aggregate validity: "VALID" (all controls pass all validators), "INVALID" (at least one control fails), "PENDING" (async validator running), or "DISABLED" (entire group disabled). form.valid is a shorthand boolean for status === "VALID". You can also subscribe to statusChanges to react to transitions.',
    },
    {
      q: 'What does form.reset() do to a FormGroup?',
      a: 'form.reset() sets the value of every control to null (or an optional initial-value object you pass) and resets all state flags: pristine (was changed? → no), untouched (was blurred? → no), and recalculates validity. The FormGroup structure itself (controls, validators) is preserved. Useful after a successful form submission to clear the form ready for the next entry.',
    },
    {
      q: 'How do you add a cross-field validator at the FormGroup level?',
      a: 'Pass the validator as the second argument to new FormGroup({}, { validators: myValidator }) or fb.group({}, { validators: myValidator }). The validator receives the entire FormGroup as an AbstractControl, so it can read any child control via group.get("field"). Return null for valid or a validation error object (e.g. { passwordMismatch: true }) for invalid. Bind the error in the template on the formGroup element.',
    },
  ];
}
