import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-template-driven-forms',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './template-driven-forms.component.html',
  styleUrl: './template-driven-forms.component.css',
})
export class TemplateDrivenFormsComponent {
  syntaxCode = [
    '// app.module.ts or standalone component imports',
    'import { FormsModule } from "@angular/forms";',
    '',
    '// Template-driven form wiring',
    '<form #f="ngForm" (ngSubmit)="onSubmit(f)">',
    '',
    '  <!-- Two-way binding with ngModel -->',
    '  <input name="email"',
    '         [(ngModel)]="user.email"',
    '         #emailCtrl="ngModel"',
    '         required email />',
    '',
    '  <!-- Validator directives on the element -->',
    '  <input name="username"',
    '         [(ngModel)]="user.username"',
    '         #usernameCtrl="ngModel"',
    '         required minlength="3" />',
    '',
    '  <!-- Show error when touched and invalid -->',
    '  <span *ngIf="emailCtrl.touched && emailCtrl.errors?.["required"]">',
    '    Email is required',
    '  </span>',
    '',
    '  <!-- Disabled until form is valid -->',
    '  <button type="submit" [disabled]="f.invalid">Submit</button>',
    '</form>',
    '',
    '// Handler receives NgForm reference',
    'import { NgForm } from "@angular/forms";',
    'onSubmit(form: NgForm) {',
    '  if (form.valid) { console.log(form.value); }',
    '}',
  ].join('\n');

  exampleCode = [
    '// login.component.ts',
    'export class LoginComponent {',
    '  user = { email: "", password: "" };',
    '',
    '  onLogin(form: NgForm) {',
    '    if (form.valid) {',
    '      console.log("Login payload:", form.value);',
    '      // call auth service here',
    '      form.reset();',
    '    }',
    '  }',
    '}',
    '',
    '<!-- login.component.html -->',
    '<form #loginForm="ngForm" (ngSubmit)="onLogin(loginForm)">',
    '',
    '  <!-- Email field -->',
    '  <label for="email">Email</label>',
    '  <input id="email" name="email" type="email"',
    '         [(ngModel)]="user.email"',
    '         #emailCtrl="ngModel"',
    '         required email />',
    '  <div *ngIf="emailCtrl.touched && emailCtrl.invalid">',
    '    <span *ngIf="emailCtrl.errors?.["required"]">Email is required.</span>',
    '    <span *ngIf="emailCtrl.errors?.["email"]">Enter a valid email.</span>',
    '  </div>',
    '',
    '  <!-- Password field -->',
    '  <label for="password">Password</label>',
    '  <input id="password" name="password" type="password"',
    '         [(ngModel)]="user.password"',
    '         #pwdCtrl="ngModel"',
    '         required minlength="6" />',
    '  <div *ngIf="pwdCtrl.touched && pwdCtrl.invalid">',
    '    <span *ngIf="pwdCtrl.errors?.["required"]">Password is required.</span>',
    '    <span *ngIf="pwdCtrl.errors?.["minlength"]">Minimum 6 characters.</span>',
    '  </div>',
    '',
    '  <button type="submit" [disabled]="loginForm.invalid">Login</button>',
    '</form>',
  ].join('\n');

  interviewQA = [
    {
      q: 'What are Template-Driven Forms and which module do they require?',
      a: 'Template-Driven Forms (TDF) are Angular\'s HTML-first forms approach where binding, validation, and structure are defined using directives in the template. They require FormsModule to be imported, which provides the NgForm, NgModel, and NgModelGroup directives.',
    },
    {
      q: 'What is the role of ngModel and how does two-way binding work in TDF?',
      a: 'ngModel creates a two-way data binding between an input element and a component property using the banana-in-a-box syntax [(ngModel)]. Internally it combines [ngModel] (property binding, model → view) and (ngModelChange) (event binding, view → model), keeping both in sync automatically.',
    },
    {
      q: 'How do you access a control\'s validation state in a template-driven form?',
      a: 'Export the ngModel directive to a template reference variable using #ctrl="ngModel". This gives access to properties like ctrl.valid, ctrl.invalid, ctrl.touched, ctrl.dirty, and ctrl.errors. For example: <input #emailCtrl="ngModel" required email> then *ngIf="emailCtrl.touched && emailCtrl.errors?.required".',
    },
    {
      q: 'What is ngModelGroup and when do you use it?',
      a: 'ngModelGroup groups related ngModel controls under a nested object key within the form value. It is useful for organizing fields like address (street, city, zip) into a sub-object. In the form value, they appear as form.value.address.city. It maps to a nested FormGroup internally.',
    },
    {
      q: 'How does (ngSubmit) work and what does the handler receive?',
      a: '(ngSubmit) is an event emitted by NgForm when the form is submitted (either via a submit button or enter key). You typically bind it as (ngSubmit)="onSubmit(f)" where f is the #f="ngForm" template reference. The handler receives an NgForm instance giving access to form.value and form.valid.',
    },
    {
      q: 'How do Template-Driven Forms compare to Reactive Forms?',
      a: 'TDF are HTML-centric: less TypeScript, faster to write, ideal for simple forms. Reactive Forms are TypeScript-centric: the model is defined in the class, making them easier to unit test (no DOM needed), better for dynamic/complex forms, and integrable with RxJS observables like valueChanges. TDF use FormsModule; Reactive Forms use ReactiveFormsModule.',
    },
    {
      q: 'What CSS classes does Angular automatically apply to form controls and what do they mean?',
      a: 'Angular adds state-tracking CSS classes automatically: ng-valid / ng-invalid (passes or fails validation), ng-touched / ng-untouched (user has blurred / never blurred), ng-dirty / ng-pristine (value changed / never changed). These enable CSS-based visual feedback (e.g. red border on .ng-invalid.ng-touched) without extra code.',
    },
  ];
}
