import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-latest-angular-updates',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './latest-angular-updates.component.html',
  styleUrl: './latest-angular-updates.component.css',
})
export class LatestAngularUpdatesComponent {

  v17Code = [
    '// Angular 17 — New Control Flow (replaces *ngIf, *ngFor, ngSwitch)',
    '',
    '// OLD (still supported)',
    '<div *ngIf="isLoggedIn; else guest">Welcome back!</div>',
    '<ng-template #guest>Please log in</ng-template>',
    '',
    '// NEW @if / @else',
    '@if (isLoggedIn) {',
    '  <p>Welcome back!</p>',
    '} @else {',
    '  <p>Please log in</p>',
    '}',
    '',
    '// OLD *ngFor with trackBy',
    '<li *ngFor="let p of products; trackBy: trackById">{{ p.name }}</li>',
    '',
    '// NEW @for (track is mandatory)',
    '@for (p of products; track p.id) {',
    '  <li>{{ p.name }}</li>',
    '} @empty {',
    '  <li>No products found.</li>',
    '}',
    '',
    '// @switch replaces [ngSwitch]',
    '@switch (status) {',
    '  @case ("active")   { <span class="green">Active</span>   }',
    '  @case ("inactive") { <span class="red">Inactive</span>   }',
    '  @default           { <span class="gray">Unknown</span>   }',
    '}',
  ].join('\n');

  v17DeferCode = [
    '// @defer — Declarative Lazy Loading (Angular 17)',
    '',
    '// Load HeavyComponent only when it enters the viewport',
    '@defer (on viewport) {',
    '  <app-heavy-chart />',
    '} @placeholder {',
    '  <div class="skeleton">Loading chart...</div>',
    '} @loading (minimum 300ms) {',
    '  <app-spinner />',
    '} @error {',
    '  <p>Failed to load. <button (click)="retry()">Retry</button></p>',
    '}',
    '',
    '// Other defer triggers:',
    '// on idle       — loads when browser is idle',
    '// on immediate  — loads right away (but still deferred bundle)',
    '// on interaction(ref) — loads on user interaction with an element',
    '// on hover(ref) — loads on mouse hover',
    '// when condition — loads when expression becomes truthy',
    '// prefetch on idle — prefetch in background',
  ].join('\n');

  v18Code = [
    '// Angular 18 — Zoneless Change Detection (Experimental)',
    '',
    '// main.ts — opt-in to zoneless',
    'bootstrapApplication(AppComponent, {',
    '  providers: [',
    '    provideExperimentalZonelessChangeDetection(),',
    '  ],',
    '});',
    '',
    '// With zoneless, change detection is signal-driven.',
    '// Remove zone.js from polyfills.ts / angular.json',
    '',
    '// Angular 18 — ng-content fallback content',
    '@Component({',
    '  template: `',
    '    <ng-content select="[header]">',
    '      <h2>Default Header</h2>  <!-- shown if nothing projected -->',
    '    </ng-content>',
    '  `',
    '})',
    'export class CardComponent {}',
    '',
    '// Angular 18 — Material 3 stable',
    '// ng add @angular/material  (choose M3 theme)',
    '',
    '// Angular 18 — Route-level render mode (SSR)',
    'export const serverRoutes: ServerRoute[] = [',
    '  { path: "home",    mode: RenderMode.Prerender },',
    '  { path: "product/:id", mode: RenderMode.Server },',
    '  { path: "**",     mode: RenderMode.Client },',
    '];',
  ].join('\n');

  v19Code = [
    '// Angular 19 — Signal-based component inputs/outputs',
    '',
    '// input() — reactive @Input replacement (Angular 19+)',
    '@Component({ ... })',
    'export class ProductCardComponent {',
    '  // Replaces @Input() product: Product',
    '  product = input.required<Product>();',
    '',
    '  // With default value',
    '  showPrice = input(true);',
    '',
    '  // Aliased input',
    '  label = input<string>("", { alias: "btnLabel" });',
    '}',
    '',
    '// output() — reactive @Output replacement',
    'export class ButtonComponent {',
    '  clicked = output<string>();',
    '',
    '  handleClick() {',
    '    this.clicked.emit("Button clicked!");',
    '  }',
    '}',
    '',
    '// model() — two-way bindable signal (like @Input + @Output pair)',
    'export class ToggleComponent {',
    '  checked = model(false);   // parent binds [(checked)]="isOn"',
    '}',
    '',
    '// viewChild() / contentChild() — signal-based queries',
    'export class ParentComponent {',
    '  chart = viewChild<ChartComponent>(ChartComponent);',
    '  // chart() returns ChartComponent | undefined (always up to date)',
    '}',
    '',
    '// linkedSignal() — derived writable signal',
    'const items = signal(["a", "b", "c"]);',
    'const selected = linkedSignal(() => items()[0]);',
    '// selected resets to items()[0] when items changes',
    '// but can also be set manually: selected.set("b")',
  ].join('\n');

  v19HydrationCode = [
    '// Angular 19 — Incremental Hydration',
    '',
    '// app.config.ts',
    'export const appConfig: ApplicationConfig = {',
    '  providers: [',
    '    provideClientHydration(withIncrementalHydration()),',
    '  ],',
    '};',
    '',
    '// Template — hydrate sections on demand',
    '@defer (hydrate on viewport) {',
    '  <app-comments />   <!-- SSR-rendered, hydrated when visible -->',
    '}',
    '',
    '@defer (hydrate on interaction) {',
    '  <app-search />     <!-- hydrated on first user interaction -->',
    '}',
    '',
    '// Angular 19 — Resource API (experimental)',
    'export class ProductComponent {',
    '  productId = input.required<number>();',
    '',
    '  // Reactive data fetching tied to signal',
    '  product = resource({',
    '    request: () => this.productId(),',
    '    loader: ({ request: id }) =>',
    '      fetch(`/api/products/${id}`).then(r => r.json()),',
    '  });',
    '  // product.value(), product.status(), product.isLoading()',
    '}',
  ].join('\n');

  v20Code = [
    '// Angular 20 — Key Improvements (May 2025)',
    '',
    '// Stable: Zoneless Change Detection',
    'bootstrapApplication(AppComponent, {',
    '  providers: [',
    '    provideZonelessChangeDetection(), // no longer "Experimental"',
    '  ],',
    '});',
    '',
    '// Stable: httpResource — signal-based HTTP fetching',
    'export class UsersComponent {',
    '  users = httpResource("/api/users");',
    '  // users.value() — response data',
    '  // users.isLoading() — loading state',
    '  // users.error() — error state',
    '}',
    '',
    '// Enhanced @let template variable (stable in v20)',
    '@let user = users.value()?.find(u => u.id === selectedId);',
    '@if (user) {',
    '  <p>{{ user.name }} — {{ user.email }}</p>',
    '}',
    '',
    '// Stable: signal-based forms (experimental in v19)',
    '// Better tree-shaking for CommonModule directives',
    '// Improved SSR / hydration performance',
    '// TypeScript 5.8 support',
  ].join('\n');

  migrationCode = [
    '// Migrating to latest Angular — key commands',
    '',
    '// Update to latest Angular (run in steps, e.g. 17 → 18 → 19 → 20)',
    'ng update @angular/core @angular/cli',
    '',
    '// Automated migration: *ngIf/*ngFor → @if/@for (Angular 17+)',
    'ng generate @angular/core:control-flow',
    '',
    '// Automated migration: module-based → standalone',
    'ng generate @angular/core:standalone',
    '',
    '// Automated migration: class-based signals → signal inputs/outputs',
    'ng generate @angular/core:signal-input-migration',
    'ng generate @angular/core:signal-queries-migration',
    'ng generate @angular/core:output-migration',
    '',
    '// Check migration guide at update.angular.io',
  ].join('\n');

  interviewQA = [
    {
      q: 'What is the new control flow syntax introduced in Angular 17 and why is it better than structural directives?',
      a: 'Angular 17 introduced built-in control flow using @if/@else, @for, and @switch blocks. It is better because: (1) No need to import CommonModule for *ngIf/*ngFor, reducing boilerplate in standalone components. (2) @for requires a "track" expression, enforcing performance best practices. (3) @for has a built-in @empty block for handling empty collections. (4) Better TypeScript type narrowing inside @if blocks — the type is narrowed in the block. (5) The syntax is more readable and closer to native JS control flow.',
    },
    {
      q: 'What is @defer in Angular 17 and what triggers are available?',
      a: '@defer is a declarative lazy loading mechanism that code-splits a component into a separate bundle and loads it based on a trigger. Triggers include: "on viewport" (enters viewport), "on idle" (browser idle), "on interaction" (user interacts with the element), "on hover", "on immediate" (as soon as possible), and "when expression" (custom boolean condition). @defer also supports @placeholder, @loading, and @error blocks for different loading states. This replaces manual intersection observer or router-based lazy loading for template sections.',
    },
    {
      q: 'What is zoneless change detection in Angular 18 and why does it matter?',
      a: 'Zoneless change detection removes the dependency on Zone.js, which monkey-patches browser APIs (setTimeout, Promise, etc.) to trigger change detection. Without Zone.js: (1) Initial bundle size reduces by ~13KB (Zone.js gzip size). (2) Change detection becomes pull-based (signal-driven) instead of push-based. (3) Better interoperability with non-Angular code and third-party libraries. (4) More predictable performance. Enable it with provideExperimentalZonelessChangeDetection() in Angular 18 or provideZonelessChangeDetection() in Angular 20 (stable).',
    },
    {
      q: 'What are the signal-based component APIs introduced in Angular 19?',
      a: 'Angular 19 introduced signal-based replacements for decorator APIs: (1) input() replaces @Input() — returns a Signal<T> instead of a plain property, enabling reactive derived computations. (2) output() replaces @Output() + EventEmitter — simpler API, no need to extend EventEmitter. (3) model() creates a two-way bindable signal — the parent uses [(property)] syntax, replacing the @Input + @Output(propertyChange) pattern. (4) viewChild() and contentChild() replace @ViewChild and @ContentChild with signal-based queries that always reflect current state.',
    },
    {
      q: 'What is linkedSignal() and when would you use it?',
      a: 'linkedSignal() creates a derived WRITABLE signal — unlike computed() which is read-only. A linked signal resets to its computed value when its dependencies change, but it can also be manually set by the user between updates. Use case: a "selected item" that defaults to the first item in a list (derived), but the user can change the selection (writable). When the list changes, the selection automatically resets to the new first item. This is useful for selection state, paginations, and filters that have a logical default but are overridable.',
    },
    {
      q: 'What is incremental hydration introduced in Angular 19?',
      a: 'Incremental hydration (Angular 19) allows SSR-rendered HTML to be hydrated in parts, on demand, rather than all at once. Combined with @defer blocks, you can annotate sections with "hydrate on viewport", "hydrate on interaction", etc. The server pre-renders all content for SEO and performance, but the JS for heavy components only loads/runs when the user actually needs it. This dramatically reduces Time to Interactive (TTI) for large pages with many components. Requires provideClientHydration(withIncrementalHydration()) in the app config.',
    },
    {
      q: 'What is the Resource API and httpResource in Angular 19-20?',
      a: 'The Resource API (experimental in Angular 19, stable in Angular 20) is a signal-based data fetching primitive. resource() takes a request signal and a loader function, and returns an object with value(), isLoading(), error(), and status() signals. httpResource() is a built-in HTTP-specific resource that takes a URL (or signal returning a URL) and automatically fetches and retypes the response. It eliminates the subscribe() pattern for simple HTTP reads and keeps the UI reactive to request parameter changes.',
    },
    {
      q: 'What is the @let syntax in Angular templates?',
      a: '@let was introduced in Angular 18 and stabilized in Angular 19-20. It creates a template-local variable that can hold any expression result, including async pipe outputs. Example: @let user = users$ | async; @if (user) { ... }. Unlike template reference variables (#ref), @let can hold computed values, not just element references. It works in scoped blocks (inside @if, @for, @switch) and avoids repeating the same complex expression multiple times. It is especially useful when working with nested async data.',
    },
  ];
}
