import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-error-interceptor',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './error-interceptor.component.html',
  styleUrl: './error-interceptor.component.css',
})
export class ErrorInterceptorComponent {
  syntaxCode = [
    '// Error Interceptor — centralized HTTP error handling',
    '',
    'import {',
    '  HttpInterceptorFn, HttpErrorResponse',
    '} from "@angular/common/http";',
    'import { inject } from "@angular/core";',
    'import { catchError, throwError } from "rxjs";',
    '',
    'export const errorInterceptor: HttpInterceptorFn = (req, next) => {',
    '  const router = inject(Router);',
    '  const toastService = inject(ToastService);',
    '  const authService = inject(AuthService);',
    '',
    '  return next(req).pipe(',
    '    catchError((error: HttpErrorResponse) => {',
    '      switch (error.status) {',
    '        case 401:',
    '          // Unauthorized — token expired or missing',
    '          authService.clearToken();',
    '          router.navigate(["/login"]);',
    '          break;',
    '',
    '        case 403:',
    '          // Forbidden — user lacks permission',
    '          toastService.error("You do not have permission to perform this action.");',
    '          router.navigate(["/forbidden"]);',
    '          break;',
    '',
    '        case 404:',
    '          toastService.warn("Resource not found.");',
    '          break;',
    '',
    '        case 500:',
    '        case 503:',
    '          toastService.error("Server error. Please try again later.");',
    '          break;',
    '',
    '        default:',
    '          toastService.error(`Unexpected error: ${error.message}`);',
    '      }',
    '      // Re-throw so services/components can also handle if needed',
    '      return throwError(() => error);',
    '    })',
    '  );',
    '};',
  ].join('\n');

  exampleCode = [
    '// Real-world: Error interceptor with retry, user notification, and logging',
    '',
    'export const errorInterceptor: HttpInterceptorFn = (req, next) => {',
    '  const router = inject(Router);',
    '  const notificationService = inject(NotificationService);',
    '  const logger = inject(LoggerService);',
    '  const authService = inject(AuthService);',
    '',
    '  return next(req).pipe(',
    '    // Retry network errors up to 2 times (not 4xx — those are client errors)',
    '    retry({',
    '      count: 2,',
    '      delay: (error: HttpErrorResponse) => {',
    '        if (error.status >= 400 && error.status < 500) {',
    '          return throwError(() => error); // Do not retry 4xx',
    '        }',
    '        return timer(1000); // Retry 5xx after 1 second',
    '      }',
    '    }),',
    '    catchError((error: HttpErrorResponse) => {',
    '      // Log all errors for observability',
    '      logger.error({',
    '        url: req.url,',
    '        method: req.method,',
    '        status: error.status,',
    '        message: error.message',
    '      });',
    '',
    '      if (error.status === 401) {',
    '        // Try refresh — if refresh also fails, logout',
    '        return authService.refreshToken().pipe(',
    '          switchMap(token => {',
    '            return next(req.clone({',
    '              setHeaders: { Authorization: `Bearer ${token}` }',
    '            }));',
    '          }),',
    '          catchError(() => {',
    '            authService.logout();',
    '            router.navigate(["/login"], {',
    '              queryParams: { returnUrl: router.url }',
    '            });',
    '            return throwError(() => error);',
    '          })',
    '        );',
    '      }',
    '',
    '      if (error.status === 403) {',
    '        notificationService.show("Access denied", "error");',
    '        router.navigate(["/access-denied"]);',
    '      } else if (error.status >= 500) {',
    '        notificationService.show("Server error — please try again", "error");',
    '      }',
    '',
    '      return throwError(() => error);',
    '    })',
    '  );',
    '};',
  ].join('\n');

  interviewQA = [
    {
      q: 'What is an error interceptor and what problems does it solve?',
      a: 'An error interceptor is an Angular HTTP interceptor that uses catchError to intercept HttpErrorResponse objects from failed API calls. It centralizes HTTP error handling — instead of every service method and component handling 401, 403, 500 errors individually, the interceptor handles them once. It can: redirect to /login on 401, show a global toast on 500, navigate to /forbidden on 403, retry failed requests, log errors to a monitoring service, and re-throw for local handling if needed.',
    },
    {
      q: 'What is HttpErrorResponse and what information does it contain?',
      a: 'HttpErrorResponse is Angular\'s class for HTTP error responses, extending HttpResponse. Key properties: status (HTTP status code: 401, 403, 404, 500), statusText (HTTP status description: "Unauthorized", "Forbidden"), error (the parsed response body — often an error message object from the server), message (the full error message string), url (the URL that failed), and name ("HttpErrorResponse"). Error responses with status 0 indicate network errors (no internet, CORS, server down) — not HTTP errors from the server.',
    },
    {
      q: 'Why must you call throwError(() => error) in catchError instead of just swallowing the error?',
      a: 'If you handle an error in the interceptor and return EMPTY or a completed Observable without re-throwing, the Observable completes successfully from the subscriber\'s perspective — the service and component will never know the request failed. This prevents components from showing error states. By calling throwError(() => error) after handling (logging, toast, redirect), you re-throw the error so that service-level and component-level error handling can still react if needed. The interceptor handles global concerns; the component may handle local UX (disable button, show field error).',
    },
    {
      q: 'How do you retry failed HTTP requests in the error interceptor?',
      a: 'Use RxJS retry() or retryWhen() operators before catchError in the pipe. Angular/RxJS provides retry({ count: 2, delay: 1000 }) for simple retry. For smart retry (only 5xx, not 4xx), use retry({ count: 2, delay: (err) => err.status >= 500 ? timer(1000) : throwError(() => err) }). Important: always place retry before catchError, and never retry 4xx errors — they are client-side issues (wrong parameters, auth failure) that won\'t be fixed by retrying. Retry only makes sense for transient network or server errors (5xx, status 0).',
    },
    {
      q: 'What is the difference between a 401 and 403 HTTP error? How should each be handled?',
      a: '401 Unauthorized means the request lacks valid authentication credentials — the user is not logged in, or the token is expired/missing. Handle by: clearing the current token and redirecting to /login (with returnUrl for post-login redirect). 403 Forbidden means the user IS authenticated but lacks the required role/permission for the requested resource. Handle by: showing an "Access Denied" message and optionally redirecting to a /forbidden page. Never log out the user on a 403 — they are authenticated, just not authorized for this specific action.',
    },
    {
      q: 'How do you prevent the error interceptor from interfering with the refresh token flow?',
      a: 'When the error interceptor triggers a token refresh on 401 and the refresh endpoint itself returns 401, you must guard against infinite loops. Common approach: (1) Check if the failing request is to the refresh endpoint: if (req.url.includes("/auth/refresh")) { authService.logout(); return throwError(() => error); } — skip refresh logic for the refresh endpoint itself; (2) Track isRefreshing state in the interceptor; (3) The BehaviorSubject queue pattern ensures only one refresh happens at a time. Without these guards, a failed refresh causes another 401, which triggers another refresh, infinitely.',
    },
    {
      q: 'How do you show a global toast notification from an HTTP interceptor?',
      a: 'Inject a singleton notification/toast service using inject() (functional interceptor) or constructor injection (class-based). Call the service method inside catchError: const toastService = inject(ToastService); return next(req).pipe(catchError(err => { if (err.status === 500) toastService.show("Server error", "error"); return throwError(() => err); })). The ToastService should use a Subject or BehaviorSubject internally and the app\'s root component (or a global toast component) subscribes to display the notifications. This decouples error detection (interceptor) from error display (component).',
    },
  ];
}
